# File: azure-pipelines/templates/buildProduct/build-and-publish-adal.yml
# Description: Template to build & publish adal library to internal maven feed

parameters:
  - name: versionNumber
  - name: commonVersionNumber
  - name: buildFlags
  - name: shouldRunUnitAndInstrumentedTests
    default: true
  - name: publishLibraryArtifacts
    default: true

jobs:
  - template: build-and-publish.yml
    parameters:
      repository: adal
      project: adal
      assembleCmd: assembleDist
      testCmd: testDistDebugUnitTest
      publishCmd: publishAdalPublicationToVsts-maven-adal-androidRepository
      dependencyParams: -PdistCommonVersion=${{ parameters.commonVersionNumber }} --configuration=distReleaseRuntimeClasspath --write-locks
      assembleParams: -PprojVersion=${{ parameters.versionNumber }} -PdistCommonVersion=${{ parameters.commonVersionNumber }} ${{ parameters.buildFlags }}
      testParams: -PprojVersion=${{ parameters.versionNumber }} -PdistCommonVersion=${{ parameters.commonVersionNumber }} -Psugar=true -PlabSecret=$(AndroidAutomationRunnerAppSecret) ${{ parameters.buildFlags }} -PshouldSkipLongRunningTest=true -PcodeCoverageEnabled=true
      publishParams: -PprojVersion=${{ parameters.versionNumber }} -PdistCommonVersion=${{ parameters.commonVersionNumber }} ${{ parameters.buildFlags }}
      vstsMvnAndroidUsername: ENV_VSTS_MVN_ANDROIDADAL_USERNAME
      vstsMvnAndroidAccessToken: ENV_VSTS_MVN_ANDROIDADAL_ACCESSTOKEN
      shouldRunUnitTests: ${{ parameters.shouldRunUnitAndInstrumentedTests }}
      shouldRunInstrumentedTests: ${{ parameters.shouldRunUnitAndInstrumentedTests }}
      publishLibraryArtifacts: ${{ parameters.publishLibraryArtifacts }}