parameters:
  - name: automationAppApkPath
    type: string
  - name: automationAppTestApkPath
    type: string
  - name: testTargetPackages
    type: string
  - name: apiLevelTarget
    type: string
  - name: resultsHistoryName
    type: string
  - name: resultsDir
    type: string
  - name: firebaseTimeout
    type: string
    default: 45m
  - name: firebaseDeviceId
    type: string
  - name: firebaseDeviceAndroidVersion
    type: number
  - name: testRunTitle
    type: string

jobs:
  - job: 'run_on_firebase'
    displayName: Running Test Suite on Firebase
    timeoutInMinutes: 90
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
      - task: DownloadSecureFile@1
        displayName: 'Download Firebase Service Account Key File'
        name: gcServiceAccountKey
        inputs:
          secureFile: AndroidFirebaseServiceAccountKey.json
          retryCount: 5
      - download: current
      - script: gcloud version
        displayName: 'Check gcloud version'
      - task: Bash@3
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $(gcServiceAccountKey.secureFilePath)
        name: runUiAutomation
        displayName: Run UI Automation on Firebase
        inputs:
          targetType: inline
          script: |
            gcloud auth activate-service-account --key-file "$(gcServiceAccountKey.secureFilePath)"
            gcloud config set project "$(gCloudProjectId)"
            gcloud firebase test android models list
            wget --quiet https://github.com/Flank/flank/releases/download/v22.05.0/flank.jar -O $(Build.SourcesDirectory)/flank.jar
            cp $(Build.SourcesDirectory)/azure-pipelines/ui-automation/templates/flank/flank.yml ./flank.yml
            java -jar $(Build.SourcesDirectory)/flank.jar firebase test android run \
              --type instrumentation \
              --app "${{ parameters.automationAppApkPath }}" \
              --test "${{ parameters.automationAppTestApkPath }}" \
              --auto-google-login \
              --record-video \
              --device model=${{ parameters.firebaseDeviceId }},version=${{ parameters.firebaseDeviceAndroidVersion }},locale=en,orientation=portrait \
              --timeout "${{ parameters.firebaseTimeout }}" \
              --other-files \
              "/data/local/tmp/CompanyPortal.apk=$(Pipeline.Workspace)/brokerapks/$(companyPortalApk),\
              /data/local/tmp/Authenticator.apk=$(Pipeline.Workspace)/brokerapks/$(authenticatorApk),\
              /data/local/tmp/OldAuthenticator.apk=$(Pipeline.WorkSpace)/brokerapks/oldAPKs/$(oldAuthenticatorApk),\
              /data/local/tmp/AzureSample.apk=$(Pipeline.Workspace)/azuresample/$(azure_sample_apk),\
              /data/local/tmp/BrokerHost.apk=$(Pipeline.WorkSpace)/brokerapks/$(brokerhost_apk),\
              /data/local/tmp/OldBrokerHost.apk=$(Pipeline.WorkSpace)/brokerapks/oldAPKs/$(brokerhost_apk),\
              /data/local/tmp/Outlook.apk=$(Pipeline.WorkSpace)/firstpartyapks/$(outlookApk),\
              /data/local/tmp/Teams.apk=$(Pipeline.WorkSpace)/firstpartyapks/$(teamsApk),\
              /data/local/tmp/Word.apk=$(Pipeline.WorkSpace)/firstpartyapks/$(wordApk)" \
              --results-dir "${{ parameters.resultsDir }}" \
              --directories-to-pull "/sdcard" \
              --use-orchestrator \
              --environment-variables "clearPackageData=true" \
              --results-history-name "${{ parameters.resultsHistoryName }}" \
              --test-targets "${{ parameters.testTargetPackages }}, ${{ parameters.apiLevelTarget }}" \
              --smart-flank-gcs-path "gs://test-lab-ffz6x9pu2y62a-is0rq7a7rwdhi/smart-flank-xml/broker-ci/JUnitReport.xml"
      - script: gsutil cp "gs://test-lab-ffz6x9pu2y62a-is0rq7a7rwdhi/${{ parameters.resultsDir }}/JUnitReport.xml" "$(Build.SourcesDirectory)"
        displayName: Download Test Result File
        condition: succeededOrFailed()
      - task: PublishTestResults@2
        displayName: Publish Test Results to ADO
        condition: succeededOrFailed()
        inputs:
          testResultsFiles: 'JUnitReport.xml'
          searchFolder: $(Build.SourcesDirectory)
          testRunTitle: '${{ parameters.testRunTitle }}'