# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: $(Build.BuildId)

trigger: none
pr: none

parameters:
- name: companyPortalLink
  displayName: Company Portal Link
  type: string
- name: authenticatorLink
  displayName: Authenticator Link
  type: string
- name: BrokerHostRC
  displayName: BrokerHost RC run ID
  type: string
- name: BrokerHostProd
  displayName: BrokerHost prod run ID
  type: string

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadPipelineArtifact@2
  displayName: 'Download RC Broker Host'
  inputs:
    buildType: specific
    project: 'fac9d424-53d2-45c0-91b5-ef6ba7a6bf26'
    definition: 1432
    artifactName: BrokerHost
    itemPattern: '**/*.apk'
    targetPath: '$(System.ArtifactsDirectory)'
    runVersion: 'specific'
    runId: ${{ parameters.BrokerHostRC }}
- script: curl -L -o Authenticator.apk  "${{ parameters.authenticatorLink }}"
  displayName: 'Download Authenticator'
- script:  curl -L -o CompanyPortal.apk "${{ parameters.companyPortalLink }}"
  displayName: 'Download Company Portal'
- script: gcloud version
  displayName: 'Check gcloud version'
