"""Release simulator — drop into the middle of a release to validate a phase.

WHY: testing a late phase from scratch is expensive (drive every earlier phase by
hand). Instead a *scenario* declares a target point; this module fast-forwards the
**real engine** to it in an isolated runs-root, so what you validate is exactly what
production would produce — no parallel reimplementation of the state machine.

HOW (Option A + freeze):
  * Earlier phases are fast-forwarded with `outcome: done` step-mocks (instant, offline)
    and gate auto-approval — the engine's own transitions, just short-circuited.
  * The TARGET phase runs for real: `data: live` exercises real `az` reads against real
    runs; `data: mock` uses the scenario's fine-grained input mocks (offline, deterministic).
  * Readiness is signed offline (auto items via `readiness.<item>` pass-mocks, attest items
    via gate.sign()).
  * `--freeze` snapshots the engine-produced state to tests/fixtures/<name>.json — a cache
    that is *generated by* this driver, so it can never drift into a hand-maintained lie.

A scenario is data, not code:

    name: mid_build_verify_open
    release_id: 2026-08
    ccd: 2026-08-26
    ccd_source: confirmed          # default: confirmed
    as_of: CCD+1                   # CCD-relative or absolute YYYY-MM-DD; default: ccd
    target: {phase: build_verify, at: open}   # at: open | gate | done
    data: live                     # live | mock (default: mock)
    approve_gates: [go_test]       # gates to auto-approve while fast-forwarding (see note)
    mocks:                         # merged last (win); fine-grained inputs or outcome mocks
      build_verify.checker_fired: { triggering: {...} }
    seed:                          # direct ReleaseState field overrides (e.g. pipeline_runs)
      owner_email: dev@example.com

`at` semantics (target phase T):
  open  — every phase before T complete; positioned at T's entry (nothing in T run).
  gate  — T's non-gate steps run; halted at T's first gate (error if T has no gate).
  done  — T fully complete (its gate auto-approved); positioned at the next phase.
"""
from __future__ import annotations

import os
from dataclasses import dataclass, field
from datetime import date
from typing import Optional

import yaml

from orchestrator import schedule
from orchestrator.state import ReleaseState
from orchestrator.engine import Orchestrator
from orchestrator import cli_common as C

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)                                   # release-agent/
SCENARIO_DIR = os.path.join(ROOT, "config", "scenarios")
FIXTURE_DIR = os.path.join(ROOT, "tests", "fixtures")
# Sim releases live in their OWN runs-root so a scenario can never clobber a real
# release that happens to share an id. Overridable via run_scenario(runs_root=...).
DEFAULT_SIM_RUNS = os.path.join(os.path.dirname(ROOT), ".sim-runs")

_AT_MODES = ("open", "gate", "done")


# ---------------------------------------------------------------- scenario I/O
def scenario_path(name: str) -> str:
    base = name if name.endswith((".yaml", ".yml")) else f"{name}.yaml"
    return base if os.path.isabs(base) else os.path.join(SCENARIO_DIR, base)


def load_scenario(name: str) -> dict:
    p = scenario_path(name)
    if not os.path.exists(p):
        raise FileNotFoundError(f"no scenario '{name}' (looked in {p})")
    with open(p, "r", encoding="utf-8") as fh:
        sc = yaml.safe_load(fh) or {}
    sc.setdefault("name", os.path.splitext(os.path.basename(p))[0])
    return sc


def list_scenarios() -> list:
    if not os.path.isdir(SCENARIO_DIR):
        return []
    return sorted(os.path.splitext(f)[0] for f in os.listdir(SCENARIO_DIR)
                  if f.endswith((".yaml", ".yml")))


# ---------------------------------------------------------------- result model
@dataclass
class SimResult:
    scenario: str
    release_id: str
    ccd: Optional[str]
    as_of: str
    target: dict
    reached: bool                       # did we land exactly at the requested target?
    stop_kind: str                      # 'open' | 'gate' | 'done' | 'blocked' | 'halted' | 'scheduled' | 'complete'
    stop_message: str
    steps_forwarded: int
    gates_approved: list = field(default_factory=list)
    problems: list = field(default_factory=list)
    frozen_to: Optional[str] = None
    runs_root: Optional[str] = None
    state: Optional[ReleaseState] = None


# ---------------------------------------------------------------- profile build
def _config_phase_ids(config: dict) -> list:
    return [p["id"] for p in config["phases"]]


def _phase_by_id(config: dict, pid: str) -> Optional[dict]:
    return next((p for p in config["phases"] if p["id"] == pid), None)


def build_mock_profile(config: dict, target_phase: str, data: str, mocks: dict) -> dict:
    """Compose the engine mock profile for a scenario.

    * Every non-gate step in a phase BEFORE the target gets `outcome: done` so the
      fast-forward is instant and offline (gates are approved by the driver instead).
    * The target phase runs for real: under `data: mock` any target step WITHOUT a
      scenario mock also gets `outcome: done` so gate/done mode can still advance;
      under `data: live` the target gets no base mock (real logic hits az).
    * Every auto readiness item gets `readiness.<item>: pass` so the entry gate signs
      offline. Scenario `mocks` win over all of the above (merged last).
    """
    ids = _config_phase_ids(config)
    if target_phase not in ids:
        raise ValueError(f"target phase '{target_phase}' not in config (have {ids})")
    tgt_idx = ids.index(target_phase)
    prof: dict = {}

    for i, phase in enumerate(config["phases"]):
        before = i < tgt_idx
        is_target = i == tgt_idx
        for step in phase["steps"]:
            if step.get("gate"):
                continue                                   # gates are never step-mockable
            key = f"{phase['id']}.{step['id']}"
            if before:
                prof[key] = {"outcome": "done", "note": "[sim] fast-forwarded"}
            elif is_target and data != "live":
                prof[key] = {"outcome": "done", "note": "[sim] target auto-advanced"}

    # Readiness auto items → pass offline (covers python-auto AND scout-assisted auto).
    for it in _readiness_items(config):
        if it.get("verify") == "auto":
            prof[f"readiness.{it['id']}"] = {"outcome": "pass", "detail": "[sim] readiness auto-pass"}

    prof.update(mocks or {})                               # scenario overrides win
    return prof


def _readiness_items(config: dict) -> list:
    path = os.path.join(ROOT, "config", "readiness.yaml")
    if not os.path.exists(path):
        return []
    with open(path, "r", encoding="utf-8") as fh:
        return (yaml.safe_load(fh) or {}).get("items", []) or []


# ---------------------------------------------------------------- clock
def resolve_as_of(scenario: dict, ccd: Optional[date]) -> Optional[date]:
    """Scenario `as_of`: absolute YYYY-MM-DD, or CCD-relative ('CCD+1', 'CCD-7', 'CCD').
    Defaults to CCD when omitted so the target phase's window is open."""
    spec = scenario.get("as_of")
    if not spec:
        return ccd
    spec = str(spec).strip()
    if spec.upper().startswith("CCD"):
        if ccd is None:
            raise ValueError("as_of is CCD-relative but the scenario has no ccd")
        return schedule.anchor_date(ccd, spec)
    d = schedule.parse_date(spec)
    if d is None:
        raise ValueError(f"bad as_of {spec!r} (expected YYYY-MM-DD or CCD±N)")
    return d


# ---------------------------------------------------------------- readiness sign
def _sign_readiness(orch: Orchestrator) -> None:
    """Sign the entry gate offline. verify() clears auto items via the readiness
    pass-mocks in the profile; sign() attests every attest item. If readiness has no
    config, sign() flips it directly."""
    attest_ids = [it["id"] for it in (orch.gate.config or {}).get("items", [])
                  if it.get("verify", "attest") == "attest"]
    orch.gate.sign(item_ids=attest_ids, note="[sim] fast-forward attest")


# ---------------------------------------------------------------- driver
def _is_auto_agent(step: dict) -> bool:
    return (step.get("owner", "agent") == "agent" and step.get("source") != "scout"
            and not step.get("attest") and not step.get("gate"))


def _fast_forward(orch: Orchestrator, config: dict, target_phase: str, mode: str,
                  approve_gates: set, max_iter: int = 2000) -> dict:
    """Drive the REAL engine until it reaches the target. Returns a stop dict
    {kind, message, forwarded, approved, problems}. Never reimplements transitions —
    it only reacts to what step_once() reports."""
    ids = _config_phase_ids(config)
    tgt_idx = ids.index(target_phase)
    approved, problems = [], []
    forwarded = 0
    attempted: set = set()      # threaded into step_once so a re-blocking PARALLEL step
                                # can't be re-run every iteration (else it spins to the cap)

    for _ in range(max_iter):
        cur_id = orch.current_phase_id()
        if cur_id is None:
            return _stop("complete", "Release complete.", forwarded, approved, problems)
        ci = ids.index(cur_id)

        # Arrived at / past the target — decide whether to stop.
        if ci > tgt_idx:
            # In 'gate' mode we should have halted AT the target's gate; passing it means
            # the target had no gate (or none was reached) — surface that, don't pretend.
            if mode == "gate":
                problems.append(f"target '{target_phase}' has no gate (or it was never reached)")
            return _stop("done", f"Past target — now at '{cur_id}'.", forwarded, approved, problems)
        if ci == tgt_idx and mode == "open":
            return _stop("open", f"Positioned at entry of '{target_phase}'.",
                         forwarded, approved, problems)

        act = orch.step_once(attempted)

        if act.kind == "ran":
            # In a PARALLEL phase a blocked auto step returns kind 'ran' (block_holds=
            # False), not 'reminder'. Detect that here so a genuine block is surfaced
            # instead of being re-run to the iteration cap.
            if act.phase and act.step:
                stp = orch.state.get_step(act.phase, act.step)
                step = _find_step(config, act.phase, act.step)
                if stp is not None and stp.status == "blocked" and _is_auto_agent(step or {}):
                    problems.append(f"blocked: {act.phase}.{act.step} — {stp.note}")
                    return _stop("blocked", f"{act.phase}.{act.step} blocked: {stp.note}",
                                 forwarded, approved, problems)
            forwarded += 1
            continue
        if act.kind == "complete":
            return _stop("complete", act.message, forwarded, approved, problems)
        if act.kind in ("readiness", "blocked", "halted", "scheduled"):
            # A hard stop the scenario didn't expect (e.g. as_of before the phase
            # window ⇒ scheduled; unsatisfied entry gate ⇒ readiness).
            problems.append(f"{act.kind}: {act.message}")
            return _stop(act.kind, act.message, forwarded, approved, problems)

        if act.kind == "gate":
            step_id = act.step
            at_target_gate = (act.phase == target_phase)
            if mode == "gate" and at_target_gate:
                return _stop("gate", act.message, forwarded, approved, problems)
            # Approve if allowed: earlier-phase gates always; target gate only in
            # 'done' mode or when explicitly listed.
            if (act.phase != target_phase) or mode == "done" or step_id in approve_gates:
                orch.approve_gate("[sim] auto-approved")
                approved.append(f"{act.phase}.{step_id}")
                forwarded += 1
                continue
            problems.append(f"gate not approved: {act.phase}.{step_id} "
                            f"(add it to approve_gates or use at: done)")
            return _stop("gate", act.message, forwarded, approved, problems)

        if act.kind == "reminder":
            step = _find_step(config, act.phase, act.step)
            stp = orch.state.get_step(act.phase, act.step)
            # A blocked AUTO agent step in the target is a genuine finding — stop and
            # surface it (that's exactly what live validation is meant to catch).
            if stp.status == "blocked" and _is_auto_agent(step or {}):
                problems.append(f"blocked: {act.phase}.{act.step} — {stp.note}")
                return _stop("blocked", f"{act.phase}.{act.step} blocked: {stp.note}",
                             forwarded, approved, problems)
            # Otherwise it's an expected scout/attest/human hold — clear it.
            if (step or {}).get("source") == "scout":
                orch.record_scout_step(act.phase, act.step, "pass", "[sim] auto-pass")
            else:
                orch.complete_step(act.phase, act.step, "[sim] auto-complete")
            forwarded += 1
            continue

        # idle / unknown — nothing to do.
        return _stop(act.kind or "idle", act.message, forwarded, approved, problems)

    problems.append(f"fast-forward exceeded {max_iter} iterations (possible loop)")
    return _stop("halted", "iteration cap hit", forwarded, approved, problems)


def _stop(kind, message, forwarded, approved, problems) -> dict:
    return {"kind": kind, "message": message, "forwarded": forwarded,
            "approved": approved, "problems": problems}


def _find_step(config: dict, phase_id: str, step_id: str) -> Optional[dict]:
    ph = _phase_by_id(config, phase_id)
    if not ph:
        return None
    return next((s for s in ph["steps"] if s["id"] == step_id), None)


# ---------------------------------------------------------------- entry point
def run_scenario(name_or_dict, runs_root: str = None, config_path: str = None,
                 freeze: bool = False, save: bool = True) -> SimResult:
    """Fast-forward the engine to a scenario's target and return a SimResult.

    `name_or_dict` is a scenario name (config/scenarios/<name>.yaml) or a scenario
    dict. State is written under `runs_root`/<release_id> (default .sim-runs) so
    follow-up CLI commands can inspect it. `freeze` also snapshots the produced state
    to tests/fixtures/<name>.json.
    """
    sc = name_or_dict if isinstance(name_or_dict, dict) else load_scenario(name_or_dict)
    config_path = config_path or C.DEFAULT_CONFIG
    runs_root = runs_root or DEFAULT_SIM_RUNS

    with open(config_path, "r", encoding="utf-8") as fh:
        config = yaml.safe_load(fh)

    release_id = sc.get("release_id")
    if not release_id:
        raise ValueError("scenario missing 'release_id'")
    target = sc.get("target") or {}
    tphase = target.get("phase")
    mode = (target.get("at") or "open").lower()
    if not tphase:
        raise ValueError("scenario target missing 'phase'")
    if mode not in _AT_MODES:
        raise ValueError(f"target.at must be one of {_AT_MODES} (got {mode!r})")
    data = (sc.get("data") or "mock").lower()

    # YAML may parse an unquoted `ccd: 2026-08-26` as a date object — normalize to an
    # ISO string so it serializes and the schedule helpers get their expected type.
    ccd_raw = sc.get("ccd")
    ccd_str = ccd_raw.isoformat() if isinstance(ccd_raw, date) else ccd_raw
    ccd = schedule.parse_date(ccd_str)
    as_of = resolve_as_of(sc, ccd)

    # Seed state (+ any direct field overrides) and build the mock profile.
    st = ReleaseState(release_id=release_id, ccd=ccd_str,
                      ccd_source=sc.get("ccd_source", "confirmed"),
                      owner_email=sc.get("owner_email"), owner_name=sc.get("owner_name"))
    for k, v in (sc.get("seed") or {}).items():
        if hasattr(st, k):
            setattr(st, k, v)

    profile = build_mock_profile(config, tphase, data, sc.get("mocks") or {})
    orch = Orchestrator(config_path, st, as_of=as_of, mocks=profile)

    _sign_readiness(orch)

    approve = set(sc.get("approve_gates") or [])
    stop = _fast_forward(orch, config, tphase, mode, approve)

    # In 'open' mode we break BEFORE the engine acts on the target, so its cached
    # cursor still points at the last completed phase. Sync it to the derived target
    # so status' "you are here" marker is correct (position itself is always derived).
    if stop["kind"] == "open":
        st.current_phase = tphase
        tp = _phase_by_id(config, tphase)
        first = next((s for s in (tp or {}).get("steps", [])
                      if not st.is_done(tphase, s["id"])), None)
        st.current_step = first["id"] if first else None
        st.status = "running"

    reached = stop["kind"] == mode
    res = SimResult(
        scenario=sc.get("name", "scenario"), release_id=release_id,
        ccd=ccd_str, as_of=as_of.isoformat() if as_of else "",
        target={"phase": tphase, "at": mode}, reached=reached,
        stop_kind=stop["kind"], stop_message=stop["message"],
        steps_forwarded=stop["forwarded"], gates_approved=stop["approved"],
        problems=stop["problems"], runs_root=runs_root, state=st)

    if save:
        C.save_state(st, runs_root, release_id)
    if freeze:
        res.frozen_to = _freeze(sc.get("name", release_id), st)
    return res


def _freeze(name: str, st: ReleaseState) -> str:
    os.makedirs(FIXTURE_DIR, exist_ok=True)
    path = os.path.join(FIXTURE_DIR, f"{name}.json")
    st.save(path)
    return path
