parameters:
  - name: commonVersion
    type: string
  - name: branch
    type: string
    default: dev
  - name: scriptPathFromSource
    type: string
    default: /azure-pipelines/scripts/queue-build.ps1
  - name: serviceConnection
    type: string
    default: Managed-Identity-WIF-Connection

jobs:
  - job: queueOneAuthTestApp
    displayName: Build and Download OneAuth Test App
    variables:
      - name: project
        value: OneAuth
      - name: definitionId
        value: 6332
      - name: url
        value: https://office.visualstudio.com/
      - name: timeout
        value: 60
      - name: oneAuthProjectId
        value : 'a4d3949e-967a-4298-8b6d-53f45f6b0704'
    timeoutInMinutes: 60
    steps:
      - checkout: self
        persistCredentials: True
      - template: ../../templates/token-from-service-connection.yml
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}
          tokenVariableName: SC-Token
      - task: PowerShell@2
        displayName: Queue and wait for OneAuth Test App Apk generation pipeline
        name: buildApk
        inputs:
          filePath: '$(Build.SourcesDirectory)${{ parameters.scriptPathFromSource }}'
          arguments: '-OrganizationUrl "$(url)" -Project "$(project)" -PipelinePAT "$(SC-Token)" -WaitTimeoutInMinutes $(timeout) -BuildDefinitionId "$(definitionId)" -Branch "${{ parameters.branch }}" -TemplateParams "{''androidCommonVersion'': ''${{ parameters.commonVersion }}''}" -BuildIdOutputVar "oneAuthBuildId"'
          workingDirectory: '$(Build.SourcesDirectory)'
      - task: AzureCLI@2
        displayName: Download OneAuth Artifact with AzureCLI
        inputs:
          azureSubscription: ${{ parameters.serviceConnection }}
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            Write-Host "Downloading artifact from build id $(oneAuthBuildId)"
            az pipelines runs artifact download --artifact-name Non-Container-OneAuthTestApp-arm64-v8a --path $(Build.ArtifactStagingDirectory)/OneAuthTestApp --run-id $(oneAuthBuildId) --org $(url) --project $(project)
      - publish: $(Build.ArtifactStagingDirectory)/OneAuthTestApp
        displayName: 'Publish OneAuth Test apk for later use'
        artifact: oneauthtestapp
