parameters:
  - name: commonVersion
    type: string
  - name: branch
    type: string
    default: dev
  - name: scriptPathFromSource
    type: string
    default: /azure-pipelines/scripts/queue-build.ps1

jobs:
  - job: queueOneAuthTestApp
    displayName: Build and Download OneAuth Test App
    variables:
      - name: definitionId
        value: 6332
      - name: timeout
        value: 120
    timeoutInMinutes: 120
    steps:
      - checkout: self
        persistCredentials: True
      - task: PowerShell@2
        displayName: Queue and wait for OneAuth Test App Apk generation pipeline
        name: buildApk
        continueOnError: true
        inputs:
          filePath: '$(Build.SourcesDirectory)${{ parameters.scriptPathFromSource }}'
          arguments: '-OrganizationUrl "https://office.visualstudio.com/" -Project "OneAuth" -PipelinePAT "$(Office-PAT)" -WaitTimeoutInMinutes 120 -BuildDefinitionId "6332" -Branch "${{ parameters.branch }}" -TemplateParams "{''androidCommonVersion'': ''${{ parameters.commonVersion }}''}"'
          workingDirectory: '$(Build.SourcesDirectory)'