parameters:
  - name: commonVersion
    type: string
  - name: branch
    type: string
    default: dev
  - name: scriptPathFromSource
    type: string
    default: /azure-pipelines/scripts/queue-build.ps1

jobs:
  - job: queueOneAuthTestApp
    displayName: Build and Download OneAuth Test App
    variables:
      - name: project
        value: OneAuth
      - name: definitionId
        value: 6332
      - name: url
        value: https://office.visualstudio.com/
      - name: timeout
        value: 60
      - name: oneAuthProjectId
        value : 'a4d3949e-967a-4298-8b6d-53f45f6b0704'
    timeoutInMinutes: 60
    steps:
      - checkout: self
        persistCredentials: True
      - task: AzureCLI@2
        inputs:
          azureSubscription: AuthSdkResourceManager
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            # if this fails, check out this bash script that includes diagnostics:
            # https://gist.github.com/johnterickson/19f80a3e969e39f1000d118739176e62
            
            # Note that the resoruce is specified to limit the token to Azure DevOps
            $accessToken = az account get-access-token --query accessToken --resource 499b84ac-1321-427f-aa17-267ca6975798 -o tsv

            # Set the access token as a secret, so it doesn't get leaked in the logs
            Write-Host "##vso[task.setsecret]aadToken"
            Write-Host "##vso[task.setvariable variable=Test-Token]aadToken"
      - task: PowerShell@2
        displayName: Queue and wait for OneAuth Test App Apk generation pipeline
        name: buildApk
        continueOnError: true
        inputs:
          filePath: '$(Build.SourcesDirectory)${{ parameters.scriptPathFromSource }}'
          arguments: '-OrganizationUrl "$(url)" -Project "$(project)" -PipelinePAT "$(Test-Token)" -WaitTimeoutInMinutes $(timeout) -BuildDefinitionId "$(definitionId)" -Branch "${{ parameters.branch }}" -TemplateParams "{''androidCommonVersion'': ''${{ parameters.commonVersion }}''}"'
          workingDirectory: '$(Build.SourcesDirectory)'
      - task: DownloadExternalBuildArtifacts@15
        displayName: 'Download OneAuth test app'
        inputs:
          connection: OneAuthServiceConnection_3
          project: $(oneAuthProjectId)
          definition: $(definitionId)
          version: $(buildApk.BrokeBuildId)
          downloadPath: '$(Build.ArtifactStagingDirectory)'
      - publish: $(Build.ArtifactStagingDirectory)/OneAuthTestApp
        displayName: 'Publish OneAuth Test apk for later use'
        artifact: oneauthtestapp
