parameters:
  - name: brokerApp
    type: string
    default: 'AutoBroker'
    values:
      - BrokerHost
      - BrokerMicrosoftAuthenticator
      - BrokerCompanyPortal
      - AutoBroker
  - name: brokerFlavor
    type: string
    default: 'Local'
    values:
      - Local
      - Dist
  - name: brokerSource
    displayName: Broker App Installation Source
    type: string
    default: LocalApk
    values:
      - LocalApk
      - PlayStore
  - name: preInstallLtw
    type: boolean
    default: false
  - name: adalVersion
    displayName: ADAL Version
    type: string
    default: ""
  - name: commonVersion
    displayName: Common Version
    type: string
    default: ""

jobs:
- job: brokerautomationapp
  displayName: Build and Publish Broker Automation app
  pool:
    vmImage: ubuntu-latest
  steps:
    - checkout: broker
      clean: true
      submodules: recursive
      persistCredentials: True
    - bash: |
        echo "##vso[task.setvariable variable=ENV_VSTS_MVN_ANDROIDADACCOUNTS_ACCESSTOKEN]$(System.AccessToken)"
      displayName: Set MVN Access Token in Environment
    - bash: |
        echo "##vso[task.setvariable variable=ENV_VSTS_MVN_OFFICE_ACCESSTOKEN]$(vstsOfficeMavenAccessToken)"
      displayName: Set Office MVN Access Token in Environment
    - task: AzureKeyVault@2
      displayName: 'Get Key vault AndroidAutomationRunnerAppSecret'
      inputs:
        azureSubscription: 'AuthSdkResourceManager'
        KeyVaultName: 'MSIDLABS'
        SecretsFilter: 'LabVaultAppSecret'
        RunAsPreJob: false
    - task: PowerShell@2
      displayName: Generate Assemble Dist Task
      inputs:
        targetType: inline
        script: |
          $assembleTask = "brokerautomationapp:assemble${{ parameters.brokerFlavor }}${{ parameters.brokerApp }}Debug -PlabSecret=$(LabVaultAppSecret) -PbrokerSource=${{ parameters.brokerSource }}"
          if (("${{ parameters.adalVersion }}" -ne "")) {
              $assembleTask = $assembleTask + " -PdistAdalVersion=" + "${{ parameters.adalVersion }}"
          }
          if (("${{ parameters.commonVersion }}" -ne "")) {
              $assembleTask = $assembleTask + " -PdistCommonVersion=" + "${{ parameters.commonVersion }}"
          }
          if ("${{ parameters.preInstallLtw }}" -eq "True") {
              $assembleTask = $assembleTask + " -PpreInstallLtw=true"
          }
          Write-Host "##vso[task.setvariable variable=AssembleTask;]$assembleTask"
    - task: Gradle@2
      displayName: 'Assemble Broker Automation App'
      inputs:
        tasks: brokerautomationapp:clean $(AssembleTask)
        publishJUnitResults: false
    - task: PowerShell@2
      displayName: Generate Assemble Test Task
      inputs:
        targetType: inline
        script: |
          $assembleTestTask = "brokerautomationapp:assemble${{ parameters.brokerFlavor }}${{ parameters.brokerApp }}DebugAndroidTest -PlabSecret=$(LabVaultAppSecret)"
          if (("${{ parameters.adalVersion }}" -ne "")) {
              $assembleTestTask = $assembleTestTask + " -PdistAdalVersion=" + "${{ parameters.adalVersion }}"
          }
          if (("${{ parameters.commonVersion }}" -ne "")) {
              $assembleTestTask = $assembleTestTask + " -PdistCommonVersion=" + "${{ parameters.commonVersion }}"
          }
          if ("${{ parameters.preInstallLtw }}" -eq "True") {
              $assembleTestTask = $assembleTestTask + " -PpreInstallLtw=true"
          }
          Write-Host "##vso[task.setvariable variable=AssembleTestTask;]$assembleTestTask"
    - task: Gradle@2
      displayName: 'Assemble Broker Automation App Instrumented Tests'
      inputs:
        tasks: $(AssembleTestTask)
        publishJUnitResults: false
    - task: CopyFiles@2
      displayName: 'Copy apks for later use in the pipeline'
      inputs:
        flattenFolders: true
        contents: '$(Build.SourcesDirectory)/brokerautomationapp/build/outputs/apk/**/*.apk'
        targetFolder: '$(Build.ArtifactStagingDirectory)/broker'
    - publish: '$(Build.ArtifactStagingDirectory)/broker'
      displayName: 'Publish apks for later use'
      artifact: brokerautomationapks
