parameters:
  - name: commonVersion
    type: string
  - name: branch
    type: string
    default: dev
  - name: scriptPathFromSource
    type: string
    default: /azure-pipelines/scripts/queue-build.ps1

jobs:
  - job: queueOneAuthTestApp
    displayName: Build and Download OneAuth Test App
    variables:
      - name: project
        value: OneAuth
      - name: definitionId
        value: 6332
      - name: url
        value: https://office.visualstudio.com/
      - name: timeout
        value: 60
      - name: oneAuthProjectId
        value : 'a4d3949e-967a-4298-8b6d-53f45f6b0704'
    timeoutInMinutes: 60
    steps:
      - checkout: self
        persistCredentials: True
      - task: AzureCLI@2
        displayName: Set up Access Token For OneAuth Pipeline Call
        inputs:
          azureSubscription: AuthSdkResourceManager
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            # if this fails, check out this bash script that includes diagnostics:
            # https://gist.github.com/johnterickson/19f80a3e969e39f1000d118739176e62
            
            # Note that the resource is specified to limit the token to Azure DevOps
            $accessToken = az account get-access-token --query accessToken --resource 499b84ac-1321-427f-aa17-267ca6975798 -o tsv

            # Set the access token as a secret, so it doesn't get leaked in the logs
            Write-Host "##vso[task.setsecret]$accessToken"
            Write-Host "##vso[task.setvariable variable=Test-Token]$accessToken"
#      - task: PowerShell@2
#        displayName: Queue and wait for OneAuth Test App Apk generation pipeline
#        name: buildApk
#        inputs:
#          filePath: '$(Build.SourcesDirectory)${{ parameters.scriptPathFromSource }}'
#          arguments: '-OrganizationUrl "$(url)" -Project "$(project)" -PipelinePAT "$(Test-Token)" -WaitTimeoutInMinutes $(timeout) -BuildDefinitionId "$(definitionId)" -Branch "${{ parameters.branch }}" -BuildIdOutputVar "oneAuthBuildId"'
#          workingDirectory: '$(Build.SourcesDirectory)'
      - task: AzureCLI@2
        displayName: Download OneAuth Artifact
        inputs:
          azureSubscription: AuthSdkResourceManager
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az pipelines runs artifact download --artifact-name OneAuthTestApp/arm64-v8a_signed_APK --path $(Build.ArtifactStagingDirectory)/OneAuthTestApp --run-id 28427207 --org $(url) --project $(project)
      - publish: $(Build.ArtifactStagingDirectory)/OneAuthTestApp
        displayName: 'Publish OneAuth Test apk for later use'
        artifact: oneauthtestapp
