parameters:
  - name: msazureServiceConnection
    type: string
  - name: msazureFeedName
    type: string
  - name: authenticatorVersionRC
    displayName: Authenticator Version
    type: string
  - name: authenticatorVersionPROD
    displayName: Authenticator Version
    type: string
  - name: oldAuthenticatorVersion
    displayName: Old Authenticator Version
    type: string
  - name: companyPortalVersionRC
    displayName: Company Portal Version
    type: string
  - name: companyPortalVersionPROD
    displayName: Company Portal Version
    type: string
  - name: oldCompanyPortalVersion
    displayName: Old Company Portal Version
    type: string
    default: '5.0.5729'
  - name: prodBrokerHostVersion
    type: string
  - name: oldBrokerHostVersion
    displayName: Old Broker host Version
    type: string
    default: '0.0.1'
  - name: brokerHostWithoutBrokerSelectionLogicVersion
    displayName: brokerHost without broker selection logic version
    type: string
    default: '0.0.4'
  - name: internalFeedName
    type: string
    default: 'AndroidAdal'
  - name: LTWFeedName
    type: string
  - name: OSServiceConnection
    displayName: Link to Windows Service Connection
    type: string
  - name: LTWVersionRC
    displayName: Link to Windows Version
    type: string
  - name: oldLTWVersion
    displayName: Old Link to Windows Version
    type: string
    default: '1.23051.78'

steps:
  - checkout: none
  - script: mkdir brokers
    displayName: 'make brokers dir'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
  - task: UniversalPackages@0
    displayName: 'Download com.azure.authenticator RC'
    inputs:
      command: 'download'
      downloadDirectory: '$(Build.ArtifactStagingDirectory)/brokers/RC'
      feedsToUse: 'external'
      externalFeedCredentials: '${{ parameters.msazureServiceConnection }}'
      feedDownloadExternal: '${{ parameters.msazureFeedName }}'
      packageDownloadExternal: 'com.azure.authenticator'
      versionDownloadExternal: '${{ parameters.authenticatorVersionRC }}'
  - task: UniversalPackages@0
    displayName: 'Download com.azure.authenticator PROD'
    inputs:
      command: 'download'
      downloadDirectory: '$(Build.ArtifactStagingDirectory)/brokers/PROD'
      feedsToUse: 'external'
      externalFeedCredentials: '${{ parameters.msazureServiceConnection }}'
      feedDownloadExternal: '${{ parameters.msazureFeedName }}'
      packageDownloadExternal: 'com.azure.authenticator'
      versionDownloadExternal: '${{ parameters.authenticatorVersionPROD }}'
  - task: UniversalPackages@0
    displayName: 'Download old authenticator (Pre v5 Broker) version from feed'
    inputs:
      command: 'download'
      downloadDirectory: '$(Build.ArtifactStagingDirectory)/brokers/OldAPKs'
      feedsToUse: 'internal'
      vstsFeed: '${{ parameters.internalFeedName }}'
      vstsFeedPackage: 'com.azure.authenticator'
      vstsPackageVersion: '${{ parameters.oldAuthenticatorVersion }}'
  - task: UniversalPackages@0
    displayName: 'Download com.microsoft.windowsintune.companyportal-signed RC'
    inputs:
      command: 'download'
      downloadDirectory: '$(Build.ArtifactStagingDirectory)/brokers/RC'
      feedsToUse: 'external'
      externalFeedCredentials: '${{ parameters.msazureServiceConnection }}'
      feedDownloadExternal: '${{ parameters.msazureFeedName }}'
      packageDownloadExternal: 'com.microsoft.windowsintune.companyportal-signed'
      versionDownloadExternal: '${{ parameters.companyPortalVersionRC }}'
  - task: UniversalPackages@0
    displayName: 'Download com.microsoft.windowsintune.companyportal-signed PROD'
    inputs:
      command: 'download'
      downloadDirectory: '$(Build.ArtifactStagingDirectory)/brokers/PROD'
      feedsToUse: 'external'
      externalFeedCredentials: '${{ parameters.msazureServiceConnection }}'
      feedDownloadExternal: '${{ parameters.msazureFeedName }}'
      packageDownloadExternal: 'com.microsoft.windowsintune.companyportal-signed'
      versionDownloadExternal: '${{ parameters.companyPortalVersionPROD }}'
  - task: UniversalPackages@0
    displayName: 'Download Old CompanyPortal Apk'
    inputs:
      command: 'download'
      downloadDirectory: '$(Build.ArtifactStagingDirectory)/brokers/OldAPKs'
      feedsToUse: 'external'
      externalFeedCredentials: '${{ parameters.msazureServiceConnection }}'
      feedDownloadExternal: '${{ parameters.msazureFeedName }}'
      packageDownloadExternal: 'com.microsoft.windowsintune.companyportal-signed'
      versionDownloadExternal: '${{ parameters.oldCompanyPortalVersion }}'
  - task: UniversalPackages@0
    displayName: 'Download PROD brokerHost version from feed'
    inputs:
      command: 'download'
      downloadDirectory: '$(Build.ArtifactStagingDirectory)/brokers/PROD'
      feedsToUse: 'internal'
      vstsFeed: '${{ parameters.internalFeedName }}'
      vstsFeedPackage: 'com.microsoft.identity.testuserapp.prod'
      vstsPackageVersion: '${{ parameters.prodBrokerHostVersion }}'
  - task: UniversalPackages@0
    displayName: 'Download old brokerHost version from feed'
    inputs:
      command: 'download'
      downloadDirectory: '$(Build.ArtifactStagingDirectory)/brokers/OldAPKs'
      feedsToUse: 'external'
      externalFeedCredentials: '${{ parameters.msazureServiceConnection }}'
      feedDownloadExternal: '${{ parameters.msazureFeedName }}'
      packageDownloadExternal: 'broker-host'
      versionDownloadExternal: '${{ parameters.oldBrokerHostVersion }}'
  - task: UniversalPackages@0
    displayName: 'Download brokerHost without broker selection logic from feed'
    inputs:
      command: 'download'
      downloadDirectory: '$(Build.ArtifactStagingDirectory)/brokers/OldAPKs'
      feedsToUse: 'external'
      externalFeedCredentials: '${{ parameters.msazureServiceConnection }}'
      feedDownloadExternal: '${{ parameters.msazureFeedName }}'
      packageDownloadExternal: 'broker-host'
      versionDownloadExternal: '${{ parameters.brokerHostWithoutBrokerSelectionLogicVersion }}'
  - task: UniversalPackages@0
    displayName: 'Download Latest RC LTW Apk'
    inputs:
      command: 'download'
      downloadDirectory: '$(Build.ArtifactStagingDirectory)/brokers/RC'
      feedsToUse: 'external'
      externalFeedCredentials: '${{ parameters.OSServiceConnection }}'
      feedDownloadExternal: '${{ parameters.LTWFeedName }}'
      packageDownloadExternal: 'com.microsoft.appmanager'
      versionDownloadExternal: '${{ parameters.LTWVersionRC }}'
  - script: mv ./YPC-*.apk ./LTW-signed.apk
    displayName: 'Rename LTW build to LTW-signed.apk'
    workingDirectory: '$(Build.ArtifactStagingDirectory)/brokers/RC'
  - task: UniversalPackages@0
    displayName: 'Download Old LTW Apk'
    inputs:
      command: 'download'
      downloadDirectory: '$(Build.ArtifactStagingDirectory)/brokers/OldAPKs'
      feedsToUse: 'external'
      externalFeedCredentials: '${{ parameters.OSServiceConnection }}'
      feedDownloadExternal: '${{ parameters.LTWFeedName }}'
      packageDownloadExternal: 'com.microsoft.appmanager'
      versionDownloadExternal: '${{ parameters.OldLTWVersion }}'
  - script: mv ./YPC-*.apk ./OldLTW-signed.apk
    displayName: 'Rename Old LTW build to OldLTW-signed.apk'
    workingDirectory: '$(Build.ArtifactStagingDirectory)/brokers/OldAPKs'
  - publish: $(Build.ArtifactStagingDirectory)/brokers
    displayName: 'Publish Broker apks for later use'
    artifact: brokerapks
