jobs:
  - job: 'download_first_party_apps'
    displayName: Download First Party Apps
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: none
      - script: mkdir firstparty
        displayName: 'Make firstparty dir'
        workingDirectory: '$(Build.ArtifactStagingDirectory)'
      - task: PythonScript@0
        displayName: 'download outlook'
        inputs:
          scriptSource: inline
          script: |
            url = 'https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=3995919&key=7d6e4758f6caf384efda114a6e6dea40b3f27de0'
            wget.download(url, '$(Build.ArtifactStagingDirectory)/firstparty/Outlook.apk')
      - task: PythonScript@0
        displayName: 'Download Teams'
        inputs:
          scriptSource: inline
          script: |
            import urllib.request
            url = 'https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=3998468&key=7f9b611e978794b6b6982e2985b1261b7080d3cc'
            path = r"$(Build.ArtifactStagingDirectory)/firstparty/Teams.apk"
            urllib.request.urlretrieve(url, path)
      - task: PythonScript@0
        displayName: 'download Word'
        inputs:
          scriptSource: inline
          script: |
            import urllib.request
            url = 'https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=3966271&key=c790de390630c91861d987f80288b4ec8a7b212b'
            path = r"$(Build.ArtifactStagingDirectory)/firstparty/Word.apk"
            urllib.request.urlretrieve(url, path)
      - publish: $(Build.ArtifactStagingDirectory)/firstparty
        displayName: 'Publish First Park APKs'
        artifact: firstpartyapks