jobs:
  - job: 'download_first_party_apps'
    displayName: Download First Party Apps
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: none
      - script: mkdir firstparty
        displayName: 'Make firstparty dir'
        workingDirectory: '$(Build.ArtifactStagingDirectory)'
      - task: PythonScript@0
        displayName: 'Download Outlook'
        inputs:
          scriptSource: inline
          script: |
            import urllib.request
            url = 'https://www.apkmirror.com/wp-content/uploads/2022/10/63/63439f7305aa4/com.microsoft.office.outlook_4.2238.1-42238819_minAPI26(arm64-v8a)(nodpi)_apkmirror.com.apk?verify=1665648340-2mOS9K6BiA6gq9gF5KMzR8oXOB7-WVDB08DLwszbBWM'
            path = r"$(Build.ArtifactStagingDirectory)/firstparty/Outlook.apk"
            urllib.request.urlretrieve(url, path)
      - task: PythonScript@0
        displayName: 'Download Teams'
        inputs:
          scriptSource: inline
          script: |
            import urllib.request
            url = 'https://www.apkmirror.com/wp-content/uploads/2022/10/36/63447681ccabf/com.microsoft.teams_1416_1.0.0.2022384401-2022384413_minAPI26(arm64-v8a)(nodpi)_apkmirror.com.apk?verify=1665649248-SpgR3K1hvb4k2A4OVJYBC_3KVcC_ga44P90Z8sj3Y8M'
            path = r"$(Build.ArtifactStagingDirectory)/firstparty/Teams.apk"
            urllib.request.urlretrieve(url, path)
      - task: PythonScript@0
        displayName: 'Download Word'
        inputs:
          scriptSource: inline
          script: |
            import urllib.request
            url = 'https://www.apkmirror.com/wp-content/uploads/2022/09/07/6336df57124df/com.microsoft.office.word_16.0.15128.20206-2002926215_minAPI26(arm64-v8a)(nodpi)_apkmirror.com.apk?verify=1665648391-9qSU8U3FlwHbvC-95Yo7guyYQSVqPcSsGByC30BajBw'
            path = r"$(Build.ArtifactStagingDirectory)/firstparty/Word.apk"
            urllib.request.urlretrieve(url, path)
      - publish: $(Build.ArtifactStagingDirectory)/firstparty
        displayName: 'Publish First Party APKs'
        artifact: firstpartyapks