# File: azure-pipelines\templates\parameters\common-params.yml
# Description: This file contains the common parameters for the pipeline

- name: customVersionNumber
  displayName: Version Number
  type: string
  default: Default
- name: flightingSelection
  displayName: Broker Flight Provider (ECS is used in PROD)
  type: string
  default: "Local"
  values:
    - Local
    - ECS
- name: flightingValueParameter
  displayName: Broker Local Flight Json-String (not active with ECS flighting)
  type: string
  default: '{EnablePrtV3:true,EnableBrokerPowerLiftLogging:true}'
- name: flagsValue
  displayName: Flags to Pass (passed to all libraries)
  type: string
  default: ' '
- name: shouldRunUiValidation
  displayName: Run E2E UI Validation?
  type: boolean
  default: False
- name: shouldRunUnitAndInstrumentedTests
  displayName: Run Unit and Instrumented Tests?
  type: boolean
  default: True
- name: shouldEnableBrokerSelectionAndDiscoveryFlag
  displayName: Should enable broker selection & discovery?
  type: boolean
  default: False
- name: shouldTrustDebugBroker
  displayName: (FOR DEBUGGING) Always trust debug broker apps. (Required for working with DEBUG CP/LTW/AuthApp)
  type: boolean
  default: false
- name: treatTestAppAsPartOfTSL
  displayName: (FOR DEBUGGING) Force Broker to treat OneAuthTestApp/MSALTestApp as first party app. (Required for testing with 1st party app registration)
  type: boolean
  default: False
- name: publishLibraryArtifacts
  displayName: Should publish library artifacts? (lockfiles and release artifacts)
  type: boolean
  default: false
- name: msalTestTarget
  displayName: Test Targets for MSAL
  type: string
  default: package com.microsoft.identity.client.msal.automationapp.testpass.broker, package com.microsoft.identity.client.msal.automationapp.testpass.msalonly, notAnnotation org.junit.Ignore, notAnnotation com.microsoft.identity.client.ui.automation.annotations.FailsWithDailyVersions, notAnnotation com.microsoft.identity.client.ui.automation.annotations.DoNotRunOnPipeline
- name: brokerTestTarget
  displayName: Test Targets for Broker
  type: string
  default: package com.microsoft.identity.client.broker.automationapp.testpass, notAnnotation org.junit.Ignore, notAnnotation com.microsoft.identity.client.ui.automation.annotations.FailsWithDailyVersions, notAnnotation com.microsoft.identity.client.ui.automation.annotations.DoNotRunOnPipeline