# File: azure-pipelines/continuous-delivery/assemble&publish.yml
# Description: Template to assemble & publish dev builds of auth client android sdk libraries to internal maven feed

parameters:
- name: repository
- name: project
- name: assembleCmd
  default: assemble
- name: testCmd
  default: test
- name: publishCmd
  default: publish
- name: dependencyParams
  default: ''
- name: assembleParams
  default: ''
- name: publishParams
  default: ''
- name: vstsMvnAndroidUsername
- name: vstsMvnAndroidAccessToken
- name: shouldPublish
  type: boolean
  default: True
- name: agentImage
  default: none
- name: shouldRunUnitTests
  type: boolean
  default: True
- name: shouldRunLinuxInlineScript
  type: boolean
  default: False
- name: linuxParams
  default: ''
  
jobs:
- job: RunUnitTest${{ parameters.project }}
  displayName: ${{ parameters.project }} UnitTest
  pool:
    vmImage: ubuntu-latest
    variables:
      - group: AndroidAuthClientVariables
  steps:
    - checkout: ${{ parameters.repository }}
      persistCredentials: True
    - task: AzureKeyVault@2
      displayName: 'Get Key vault AndroidAutomationRunnerAppSecret'
      inputs:
        azureSubscription: 'MSIDLABS_ANDROID_KV'
        KeyVaultName: 'ADALTestInfo'
        SecretsFilter: 'AndroidAutomationRunnerAppSecret'
        RunAsPreJob: false
    - task: Bash@3
      condition: eq(${{ parameters.shouldRunLinuxInlineScript }}, 'True')
      retryCountOnTaskFailure: 3
      displayName: Linux Testing Setup
      inputs:
        workingDirectory: $(Build.SourcesDirectory)/broker-java-root
        targetType: 'inline'
        script: |
          sudo apt-get install -y dbus-x11
          sudo apt-get install -y dos2unix
          dos2unix gradlew
          chmod +x gradlew
          export DISPLAY=:0.0
          eval $(dbus-launch --sh-syntax)
          sudo apt install gnome-keyring
          /usr/bin/gnome-keyring-daemon --start --components=secrets
          ./gradlew LinuxBroker:linuxBrokerUnitTestCoverageReport -PcodeCoverageEnabled=true -Psystemd_mode_enabled=false --build-cache --info
    - task: Gradle@3
      condition: neq(${{ parameters.shouldRunLinuxInlineScript }}, 'True')
      displayName: Run Test ${{ parameters.project }}
      enabled: ${{ parameters.shouldRunUnitTests }}
      continueOnError: true
      inputs:
        tasks: ${{ parameters.project }}:${{ parameters.testCmd}} ${{ parameters.assembleParams}} -Psugar=true -PlabSecret=$(AndroidAutomationRunnerAppSecret) -PshouldSkipLongRunningTest=true -PcodeCoverageEnabled=true ${{ parameters.linuxParams}}
        testRunTitle: '${{ parameters.project }}_UnitTests'
      env:
        ${{ parameters.vstsMvnAndroidUsername }}: $(AndroidAuthClient-Internal-Maven-Username)
        ${{ parameters.vstsMvnAndroidAccessToken }}: $(System.AccessToken)
    - task: PublishCodeCoverageResults@1
      displayName: Publish Code Coverage Report
      inputs:
        summaryFileLocation: '$(Build.SourcesDirectory)/${{ parameters.project }}/build/reports/jacoco/${{ parameters.testCmd }}/${{ parameters.testCmd }}.xml'
        reportDirectory: '$(Build.SourcesDirectory)/${{ parameters.project }}/build/reports/jacoco/${{ parameters.testCmd }}/html'
