# File: azure-pipelines/continuous-delivery/auth-client-android-dev.yml
# Description: Assemble & publish dev builds of auth client android sdk libraries to internal maven feed
#  Libraries include common4j, common, broker4j, linux broker, broker, msal and adal
# Variable: 'mvnUserName' user name to access internal maven feed
# Variable: 'mvnAccessToken' access token to access internal maven feed

name: 0.0.$(Date:yyyyMMdd)-dev$(Rev:.r) # $(Build.BuildNumber) = name

pr: none
trigger: none

schedules:
  - cron: "0 6 * * 1-6" # 6:00 AM UTC everyday Mon-Sat
    displayName: Auth Client Android SDK dev build
    branches:
      include:
      - master
    always: true

resources:
  repositories:
    - repository: common
      type: github
      name: AzureAD/microsoft-authentication-library-common-for-android
      ref: $(commonBranch)
      endpoint: ANDROID_GITHUB
    - repository: broker
      type: github
      name: AzureAD/ad-accounts-for-android
      ref: $(brokerBranch)
      endpoint: ANDROID_GITHUB
    - repository: msal
      type: github
      name: AzureAD/microsoft-authentication-library-for-android
      ref: $(msalBranch)
      endpoint: ANDROID_GITHUB
    - repository: adal
      type: github
      name: AzureAD/azure-activedirectory-library-for-android
      ref: $(adalBranch)
      endpoint: ANDROID_GITHUB

variables:
  versionNumber: $(Build.BuildNumber)
  projVersionParam: -PprojVersion=$(versionNumber)
  common4jVersionParam: -PdistCommon4jVersion=$(versionNumber)
  broker4jVersionParam: -PdistBroker4jVersion=$(versionNumber)
  commonVersionParam: -PdistCommonVersion=$(versionNumber)
  linuxBrokerVersion: -PlinuxBrokerVersion=$(versionNumber)
  androidProjectDependencyParam: --configuration=distReleaseRuntimeClasspath --write-locks
  javaProjectDependencyParam: --configuration=runtimeClasspath --write-locks

stages:
# Common4j - Build and publish
- stage: 'publishCommon4jLibraries'
  displayName: Common4j - Build and publish
  jobs:
  - template: assemble&publish.yml
    parameters:
      repository: common
      project: common4j
      dependencyParams: $(javaProjectDependencyParam)
      assembleParams: $(projVersionParam)
      publishParams: $(projVersionParam)
      vstsMvnAndroidUsername: ENV_VSTS_MVN_ANDROIDCOMMON_USERNAME
      vstsMvnAndroidAccessToken: ENV_VSTS_MVN_ANDROIDCOMMON_ACCESSTOKEN
# Common - Build and publish
- stage: 'publishCommonLibraries'
  displayName: Common - Build and publish
  dependsOn: publishCommon4jLibraries
  jobs:
  - template: assemble&publish.yml
    parameters:
      repository: common
      project: common
      assembleCmd: assembleDist
      publishCmd: publishDistReleasePublicationToVsts-maven-adal-androidRepository
      dependencyParams: $(androidProjectDependencyParam)
      assembleParams: $(projVersionParam) $(common4jVersionParam)
      publishParams: $(projVersionParam) $(common4jVersionParam)
      vstsMvnAndroidUsername: ENV_VSTS_MVN_ANDROIDCOMMON_USERNAME
      vstsMvnAndroidAccessToken: ENV_VSTS_MVN_ANDROIDCOMMON_ACCESSTOKEN
# Broker4j - Build and publish
- stage: 'publishBroke4jLibraries'
  displayName: Broker4j - Build and publish
  dependsOn: publishCommon4jLibraries
  jobs:
  - template: assemble&publish.yml
    parameters:
      repository: broker
      project: broker4j
      publishCmd: publishAarPublicationToVsts-maven-adal-androidRepository
      dependencyParams: $(common4jVersionParam) $(javaProjectDependencyParam)
      assembleParams: $(projVersionParam) $(common4jVersionParam)
      publishParams: $(projVersionParam) $(common4jVersionParam)
      vstsMvnAndroidUsername: ENV_VSTS_MVN_ANDROIDADACCOUNTS_USERNAME
      vstsMvnAndroidAccessToken: ENV_VSTS_MVN_ANDROIDADACCOUNTS_ACCESSTOKEN
# Broker - Build and publish
- stage: 'publishBrokeLibraries'
  displayName: Broker - Build and publish
  dependsOn: publishCommonLibraries
  jobs:
  - template: assemble&publish.yml
    parameters:
      repository: broker
      project: AADAuthenticator
      assembleCmd: assembleDist
      publishCmd: publishAdAccountsPublicationToVsts-maven-adal-androidRepository
      dependencyParams: $(androidProjectDependencyParam)
      assembleParams: $(projVersionParam) $(broker4jVersionParam) $(commonVersionParam)
      publishParams: $(projVersionParam) $(broker4jVersionParam) $(commonVersionParam)
      vstsMvnAndroidUsername: ENV_VSTS_MVN_ANDROIDADACCOUNTS_USERNAME
      vstsMvnAndroidAccessToken: ENV_VSTS_MVN_ANDROIDADACCOUNTS_ACCESSTOKEN
# Linux Broker - Build and publish
- stage: 'publishLinuxBrokeLibraries'
  displayName: Linux Broker - Build and publish
  dependsOn: 
  - publishCommon4jLibraries
  - publishBroke4jLibraries
  jobs:
  - template: assemble&publish.yml
    parameters:
      repository: broker
      project: LinuxBroker
      publishCmd: publishAarPublicationToVsts-maven-adal-androidRepository
      dependencyParams: $(broker4jVersionParam) $(common4jVersionParam) $(javaProjectDependencyParam)
      assembleParams: $(projVersionParam) $(broker4jVersionParam) $(common4jVersionParam)
      publishParams: $(projVersionParam) $(broker4jVersionParam) $(common4jVersionParam)
      vstsMvnAndroidUsername: ENV_VSTS_MVN_ANDROIDADACCOUNTS_USERNAME
      vstsMvnAndroidAccessToken: ENV_VSTS_MVN_ANDROIDADACCOUNTS_ACCESSTOKEN
  - job: PublishLinuxBrokerPackage
    dependsOn: publishLinuxBrokerLibraries
    displayName: Publish Linux Broker Package
    pool:
      vmImage: ubuntu-latest
    variables:
    - group: AndroidAuthClientVariables
    steps:
    - checkout: broker
      persistCredentials: True
    - task: Gradle@3
      displayName: Build and publish linux broker package
      env:
        ENV_VSTS_MVN_ANDROIDADACCOUNTS_USERNAME: $(AndroidAuthClient-Internal-Maven-Username)
        ENV_VSTS_MVN_ANDROIDADACCOUNTS_ACCESSTOKEN: $(AndroidAuthClient-Internal-Maven-Access-Token)
      inputs:
        cwd: $(Build.SourcesDirectory)/broker-java-root
        tasks: LinuxBrokerPackage:clean LinuxBrokerPackage:buildDeb $(linuxBrokerVersion) --build-cache --info
        publishJUnitResults: false
        jdkArchitecture: x86
        sqAnalysisBreakBuildIfQualityGateFailed: false
    - task: CopyFiles@2
      name: CopyFiles1
      displayName: Copy Files to Artifact Staging Directory
      inputs:
        SourceFolder: LinuxBrokerPackage/build/distributions
        TargetFolder: $(build.artifactstagingdirectory)
    - task: PublishPipelineArtifact@1
      name: PublishPipelineArtifacts1
      displayName: 'Publish Artifact: LinuxBrokerPackage Linux Test App Deb'
      inputs:
        ArtifactName: LinuxBrokerPackage Deb Package
        TargetPath: $(build.artifactstagingdirectory)
# Msal - Build and publish      
- stage: 'publishMsal'
  displayName: Msal - Build and publish
  dependsOn: publishCommonLibraries
  jobs:
  - template: assemble&publish.yml
    parameters:
      repository: msal
      project: msal
      assembleCmd: assembleDistRelease
      publishCmd: publishMsalPublicationToVsts-maven-adal-androidRepository 
      dependencyParams: $(androidProjectDependencyParam)
      assembleParams: $(projVersionParam) $(commonVersionParam)
      publishParams: $(projVersionParam) $(commonVersionParam)
      vstsMvnAndroidUsername: ENV_VSTS_MVN_ANDROID_MSAL_USERNAME
      vstsMvnAndroidAccessToken: ENV_VSTS_MVN_ANDROID_MSAL_ACCESSTOKEN
# Adal - Build and publish
- stage: 'publishAdal'
  displayName: Adal - Build and publish
  dependsOn: publishCommonLibraries
  jobs:
  - template: assemble&publish.yml
    parameters:
      repository: adal
      project: adal
      assembleCmd: assembleDist
      publishCmd: publishAdalPublicationToVsts-maven-adal-androidRepository 
      dependencyParams: $(androidProjectDependencyParam)
      assembleParams: $(projVersionParam) $(commonVersionParam)
      publishParams: $(projVersionParam) $(commonVersionParam)
      vstsMvnAndroidUsername: ENV_VSTS_MVN_ANDROIDADAL_USERNAME
      vstsMvnAndroidAccessToken: ENV_VSTS_MVN_ANDROIDADAL_ACCESSTOKEN
...
