# File: azure-pipelines/continuous-delivery/auth-client-android-dev.yml
# Description: Assemble & publish dev builds of auth client android sdk libraries to internal maven feed
#  Libraries include common4j, common, broker4j, broker, msal and adal
# Variable: 'mvnUserName' user name to access internal maven feed
# Variable: 'mvnAccessToken' access token to access internal maven feed

name: 0.0.$(Date:yyyyMMdd)-dev$(Rev:.r) # $(Build.BuildNumber) = name

pr: none
trigger: none

schedules:
  - cron: "0 22 * * 1-5" # 10 PM everyday Mon-Fri
    displayName: Auth Client Android SDK dev build
    branches:
      include:
      - master
    always: true

resources:
  repositories:
    - repository: common
      type: github
      name: AzureAD/microsoft-authentication-library-common-for-android
      ref: $(commonBranch)
      endpoint: ANDROID_GITHUB
    - repository: broker
      type: github
      name: AzureAD/ad-accounts-for-android
      ref: $(brokerBranch)
      endpoint: ANDROID_GITHUB
    - repository: msal
      type: github
      name: AzureAD/microsoft-authentication-library-for-android
      ref: $(msalBranch)
      endpoint: ANDROID_GITHUB
    - repository: adal
      type: github
      name: AzureAD/azure-activedirectory-library-for-android
      ref: $(adalBranch)
      endpoint: ANDROID_GITHUB

variables:
  versionNumber: $(Build.BuildNumber)
  projVersionParam: -PprojVersion=$(versionNumber)
  common4jVersionParam: -PdistCommon4jVersion=$(versionNumber)
  broker4jVersionParam: -PdistBroker4jVersion=$(versionNumber)
  commonVersionParam: -PdistCommonVersion=$(versionNumber)

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'publishCommonLibraries'
  displayName: Common - Build and publish
  pool:
    vmImage: ubuntu-latest
  jobs:
    - job: publishCommonLibraries
      displayName: Build and publish common4j and android common to internal maven feed
      steps:
      - checkout: common
        persistCredentials: True
        clean: true
      - task: Gradle@3
        displayName: Build and publish common4j
        env:
          ENV_VSTS_MVN_ANDROIDCOMMON_USERNAME: $(mvnUserName)
          ENV_VSTS_MVN_ANDROIDCOMMON_ACCESSTOKEN: $(mvnAccessToken)
        inputs:
          tasks: common4j:assemble $(projVersionParam)
      - task: CopyFiles@2
        displayName: Copy Build output to Artifact Directory
        inputs:
          SourceFolder: $(Build.SourcesDirectory)/common4j/build/
          TargetFolder: '$(System.ArtifactsDirectory)/buildOutput'
      - task: ManifestGeneratorTask@0
        displayName: 'Manifest Generation Task'
        inputs:
          BuildDropPath: '$(System.ArtifactsDirectory)/buildOutput'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(System.ArtifactsDirectory)/buildOutput'
          artifact: 'SBOM'
          publishLocation: 'pipeline'
...
