name: $(date:yyyyMMdd)$(rev:.r)

trigger: none

resources:
  repositories:
    - repository: self
      type: git
      ref: dev

pool:
  name: Hosted Windows 2019 with VS2019

jobs:
  - job: queue_build
    displayName: Queue Build
    steps:
      - checkout: self
        clean: true
        submodules: recursive
        persistCredentials: True
      - task: PowerShell@2
        inputs:
          filePath: '/azure-pipelines/scripts/queue-build.ps1'
          arguments: '-OrganizationUrl="https://msazure.visualstudio.com/" -Project="One" -PipelinePAT=$(pipelinepat) -BuildDefinitionId="301574" -PipelineVariablesJson "{ ''var1'': ''val1'', ''var2'': ''val2'' }" -Branch "working"'
...
