name: $(date:yyyyMMdd)$(rev:.r)

trigger: none

resources:
  repositories:
    - repository: self
      type: git
      ref: master

pool:
  name: Hosted Windows 2019 with VS2019

jobs:
  - job: job1
    displayName: Job1
    steps:
      - checkout: self
        clean: true
        submodules: recursive
        persistCredentials: True
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            
            Write-Host "Job1"
          workingDirectory: '$(Build.SourcesDirectory)'
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  - job: job2
    displayName: 
    dependsOn: job1
    steps:
      - checkout: self
        clean: true
        submodules: recursive
        persistCredentials: True
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            
            Write-Host "Job2"
          workingDirectory: '$(Build.SourcesDirectory)'
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  - job: job3
    displayName: Job3
    dependsOn:
      - job1
      - job2
    steps:
      - checkout: self
        clean: true
        submodules: recursive
        persistCredentials: True
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            
            Write-Host "Job3"
          workingDirectory: '$(Build.SourcesDirectory)'
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
...
