name: $(date:yyyyMMdd)$(rev:.r)

trigger: none

resources:
  repositories:
    - repository: self
      type: git
      ref: master

pool:
  name: Hosted Windows 2019 with VS2019

jobs:
  - job: Testing
    displayName: Trying
    steps:
      - checkout: none
        clean: true
        submodules: recursive
        persistCredentials: True
      - task: PowerShell@2
        inputs:
          targetType: inline
          script: |
            Write-Host "Starting task"
            Write-Host "Waiting for some time"
            Start-Sleep -Seconds 5
            Write-Host "##vso[task.setvariable variable=pipeVar1;]updatedInPipeline"
            Write-Host "##vso[task.setvariable variable=pipeVar2;]createdInPipeline"
            Write-Host "Finishing task"
...
