name: $(date:yyyyMMdd)$(rev:.r)

trigger: none

resources:
  repositories:
    - repository: self
      type: git
      ref: master

pool:
  name: Hosted Windows 2019 with VS2019

jobs:
  - job: queue_build
    displayName: Queue Build
    steps:
      - checkout: self
        clean: true
        submodules: recursive
        persistCredentials: True
      - task: PowerShell@2
        inputs:
          filePath: '$(Build.SourcesDirectory)\azure-pipelines\scripts\queue-build.ps1'
          arguments: '-OrganizationUrl "https://identitydivision.visualstudio.com/" -Project "Engineering" -PipelinePAT "$env:SYSTEM_ACCESSTOKEN" -BuildDefinitionId "1490" -PipelineVariablesJson "{ ''var1'': ''$(Build.BuildNumber)'', ''var2'': ''val2'' }" -Branch "master"'
          workingDirectory: '$(Build.SourcesDirectory)'
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
...
