# run broker UI automation testcases
# Variable: 'ENV_VSTS_MVN_ANDROIDADACCOUNTS_USERNAME' was defined in the Variables tab
# Variable: 'gCloudProjectId' was defined in the Variables tab
# Variable: 'mvnAccessToken' was defined in the Variables tab
name: $(Build.BuildId)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

resources:
  repositories:
  - repository: msal
    type: github
    name: AzureAD/microsoft-authentication-library-for-android
    ref: $(msal_branch)
    endpoint: ANDROID_GITHUB
  - repository: broker
    type: github
    name: AzureAD/ad-accounts-for-android
    ref: $(broker_branch)
    endpoint: ANDROID_GITHUB

variables:
  engineeringProjectId: 'fac9d424-53d2-45c0-91b5-ef6ba7a6bf26'
  azureSamplePipelineId: 1458
  brokerHostPipelineId: 1432
  msazureServiceConnection: AndroidBroker-CI
  msazureFeedName: Android-Broker
  msalApp: msalautomationapp-dist-AutoBroker-debug.apk
  msalTestApp: msalautomationapp-dist-AutoBroker-debug-androidTest.apk
  brokerApp: brokerautomationapp-dist-AutoBroker-debug.apk
  brokerTestApp: brokerautomationapp-dist-AutoBroker-debug-androidTest.apk
  companyPortalApk: com.microsoft.windowsintune.companyportal-signed.apk
  authenticatorApk: app-production-universal-release-signed.apk
  oldAuthenticatorApk: app-production-universal-release-signed.apk
  firebaseTimeout: 45m
  resultsHistoryName: Broker Release

parameters:
- name: firebaseDeviceId
  displayName: Firebase Device Id
  type: string
  default: blueline
- name: firebaseDeviceAndroidVersion
  displayName: Firebase Device Android Version
  type: number
  default: 28
- name: authenticatorVersion
  displayName: Authenticator Version
  type: string
  default: '*'
- name: oldAuthenticatorVersion
  displayName: Old Authenticator Version
  type: string
  default: '6.2202.*'
- name: companyPortalVersion
  displayName: Company Portal Version
  type: string
  default: '*'
- name: oldBrokerHostVersion
  displayName: Old Broker host Version
  type: string
  default: '0.0.1'
- name: msalTestTarget
  displayName: Test Targets for MSAL
  type: string
  default: package com.microsoft.identity.client.msal.automationapp.testpass.broker, notPackage com.microsoft.identity.client.msal.automationapp.testpass.broker.atpop.update, notAnnotation org.junit.Ignore, notAnnotation com.microsoft.identity.client.ui.automation.annotations.DoNotRunOnPipeline
- name: brokerTestTarget
  displayName: Test Targets for Broker
  type: string
  default: package com.microsoft.identity.client.broker.automationapp.testpass, notPackage com.microsoft.identity.client.broker.automationapp.testpass.local.adal, notAnnotation org.junit.Ignore, notAnnotation com.microsoft.identity.client.ui.automation.annotations.DoNotRunOnPipeline

stages:
# msalautomationapp
- stage: 'msalautomationapp'
  dependsOn: []    # this removes the implicit dependency on previous stage and causes this to run in parallel
  displayName: Build MSAL Automation APKs
  jobs:
    - template: ./templates/build-msal-automation-app.yml
      parameters:
        brokerApp: AutoBroker
        msalFlavor: Dist
        brokerSource: LocalApk
# brokerautomationapp
- stage: 'brokerautomationapp'
  dependsOn: []    # this removes the implicit dependency on previous stage and causes this to run in parallel
  displayName: Build Broker Automation APKs
  jobs:
    - template: ./templates/build-broker-automation-app.yml
      parameters:
        brokerApp: AutoBroker
        brokerFlavor: Dist
        brokerSource: LocalApk
# Brokers
- stage: 'brokers'
  dependsOn: []    # this removes the implicit dependency on previous stage and causes this to run in parallel
  displayName: Brokers and Azure Sample APKs
  jobs: 
    - template: ./templates/build-brokers.yml
      parameters:
        engineeringProjectId: '$(engineeringProjectId)'
        azureSamplePipelineId: '$(azureSamplePipelineId)'
        msazureServiceConnection: '$(msazureServiceConnection)'
        msazureFeedName: '$(msazureFeedName)'
        authenticatorVersion: ${{ parameters.authenticatorVersion }}
        oldAuthenticatorVersion: ${{ parameters.oldAuthenticatorVersion }}
        companyPortalVersion: ${{ parameters.companyPortalVersion }}
        brokerHostPipelineId: '$(brokerHostPipelineId)'
        oldBrokerHostVersion: ${{ parameters.oldBrokerHostVersion }}
# MSAL with Broker Test Plan stage (high API)
- stage: 'msal_with_broker_high_api'
  dependsOn:
  - msalautomationapp
  - brokers
  displayName: Running MSAL with Broker Test Plan (API 30+)
  jobs:
    - template: ./templates/run-on-firebase.yml
      parameters:
        automationAppApkPath: "$(Pipeline.Workspace)/msalautomationapks/$(msalApp)"
        automationAppTestApkPath: "$(Pipeline.Workspace)/msalautomationapks/$(msaltestApp)"
        testTargetPackages: ${{ parameters.msalTestTarget }}
        resultsHistoryName: "$(resultsHistoryName)"
        resultsDir: "msalautomationapp-testpass-broker-$(Build.BuildId)-$(Build.BuildNumber)"
        firebaseDeviceId: ${{ parameters.firebaseDeviceId }}
        firebaseDeviceAndroidVersion: ${{ parameters.firebaseDeviceAndroidVersion }}
        testRunTitle: "Broker(MSAL) UI Automation - Build # $(Build.BuildNumber)"
        apiLevelTarget: "notAnnotation com.microsoft.identity.client.ui.automation.annotations.RunOnAPI29Minus"
# MSAL with Broker Test Plan stage (low API)
- stage: 'msal_with_broker_low_api'
  dependsOn:
    - msalautomationapp
    - brokers
  displayName: Running MSAL with Broker Test Plan (API 29-)
  jobs:
    - template: ./templates/run-on-firebase.yml
      parameters:
        automationAppApkPath: "$(Pipeline.Workspace)/msalautomationapks/$(msalApp)"
        automationAppTestApkPath: "$(Pipeline.Workspace)/msalautomationapks/$(msaltestApp)"
        testTargetPackages: ${{ parameters.msalTestTarget }}
        resultsHistoryName: "$(resultsHistoryName)"
        resultsDir: "msalautomationapp-testpass-broker-$(Build.BuildId)-$(Build.BuildNumber)"
        firebaseDeviceId: blueline
        firebaseDeviceAndroidVersion: 28
        testRunTitle: "Broker(MSAL) UI Automation - Build # $(Build.BuildNumber)"
        apiLevelTarget: "annotation com.microsoft.identity.client.ui.automation.annotations.RunOnAPI29Minus"

# ADAL with Broker Test Plan stage
- stage: 'adal_with_broker'
  dependsOn:
  - brokerautomationapp
  - brokers
  displayName: ADAL with broker and Broker basic validation test plan
  jobs:
    - template: ./templates/flank/run-on-firebase-with-flank.yml
      parameters:
        automationAppApkPath: "$(Pipeline.Workspace)/brokerautomationapks/$(brokerApp)"
        automationAppTestApkPath: "$(Pipeline.Workspace)/brokerautomationapks/$(brokertestApp)"
        testTargetPackages: ${{ parameters.brokerTestTarget }}
        resultsHistoryName: "$(resultsHistoryName)"
        resultsDir: "brokerautomationapp-testpass-adal&basic-$(Build.BuildId)-$(Build.BuildNumber)"
        firebaseDeviceId: ${{ parameters.firebaseDeviceId }}
        firebaseDeviceAndroidVersion: ${{ parameters.firebaseDeviceAndroidVersion }}
        testRunTitle: "Broker(ADAL) UI Automation - Build # $(Build.BuildNumber)"
