name: $(Build.BuildId)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

parameters:  
  - name: brokerProdPipelineId
    type: string  
    default: Broker Pipeline ID
  - name: brokerPackage
    type: string
    default: com.azure.authenticator
    displayName: Broker Package
  - name: brokerVersion
    displayName: Broker Version
    type: string
    default: 0.0.1

variables:
  oneProjectId: d38b6128-1817-4bd0-a589-8dfdfcd0225b
  internalFeedName: OneProdBrokerApks

jobs:
  - job: 'download_and_publish'
    displayName: Download And Publish Brokers to Universal Packages
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: none
      - task: DownloadPipelineArtifact@2
        displayName: 'Download latest Azure Sample'
        inputs:
          buildType: 'specific'
          project: '$(oneProjectId)'
          definition: '${{ parameters.brokerProdPipelineId }}'
          artifactName: BrokerProdApk
          itemPattern: '**/*.apk'
          targetPath: '$(Build.ArtifactStagingDirectory)/broker/prod'
          buildVersionToDownload: 'latest'
      - task: UniversalPackages@0
        displayName: 'Publish Broker Apk'
        inputs:
          command: 'publish'
          downloadDirectory: '$(Build.ArtifactStagingDirectory)/broker/prod'
          feedsToUse: 'internal'
          vstsFeed: '$(internalFeedName)'
          vstsFeedPackage: '${{ parameters.brokerPackage }}'
          vstsPackageVersion: '${{ parameters.brokerVersion }}'
...
