parameters:
  - name: feedName
    type: string
    default: 'AndroidAdal'
  - name: LTWVersion
    type: string
    default: '*'
  - name: artifactPath
    type: string
    default: 'brokers'
  - name: packageName
    type: string
    default: 'com.microsoft.appmanager'
  - name: apkName
    type: string
    default: 'LTW-signed.apk'
  - name: artifactName
    type: string
    default: "LTW"
  - name: shouldPublishArtifact
    type: boolean
    default: true

steps:
  - script: mkdir -p brokers
    displayName: 'make brokers dir'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
  - task: UniversalPackages@0
    displayName: 'Download LTW from Feed'
    inputs:
      command: 'download'
      downloadDirectory: '$(Build.ArtifactStagingDirectory)/${{ parameters.artifactPath }}'
      feedsToUse: 'internal'
      vstsFeed: '${{ parameters.feedName }}'
      vstsFeedPackage: '${{ parameters.packageName }}'
      vstsPackageVersion: '${{ parameters.LTWVersion }}'
  - script: mv ./YPC-*.apk ./${{ parameters.apkName }}
    displayName: 'Rename LTW apk (${{parameters.apkName}})'
    workingDirectory: '$(Build.ArtifactStagingDirectory)/${{ parameters.artifactPath }}'
  - publish: $(Build.ArtifactStagingDirectory)/brokers
    enabled: ${{ parameters.shouldPublishArtifact }}
    displayName: 'Publish as Artifact'
    artifact: ${{ parameters.artifactName }}
  - task: PowerShell@2
    displayName: Add LTW Version Tag
    inputs:
      targetType: inline
      script: |
        Write-Host "##vso[build.addbuildtag]LTW-APK-Version=${{ parameters.LTWVersion }}"
