parameters:
  - name: feedName
    type: string
    default: 'AndroidAdal'
  - name: artifactPath
    type: string
    default: 'brokers'
  - name: companyPortalVersion
    type: string
    default: '*'
  - name: packageName
    type: string
    default: 'com.microsoft.windowsintune.companyportal-signed'
  - name: artifactName
    type: string
    default: "CompanyPortal"
  - name: shouldPublishArtifact
    type: boolean
    default: true

steps:
  - script: mkdir -p brokers
    displayName: 'make brokers dir'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
  - task: AzureCLI@2
    displayName: Download CP from External feed with Service Connection
    inputs:
      azureSubscription: AuthClientAndroid-Managed-Identity-WIF-Connection
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az artifacts universal download --organization https://msazure.visualstudio.com/ --feed Android-Broker --name ${{ parameters.packageName }} --version 5.0.628211147 --path $(Build.ArtifactStagingDirectory)/${{ parameters.artifactPath }}
#  - task: UniversalPackages@0
#    displayName: 'Download CompanyPortal from Feed'
#    inputs:
#      command: 'download'
#      downloadDirectory: '$(Build.ArtifactStagingDirectory)/${{ parameters.artifactPath }}'
#      feedsToUse: 'internal'
#      vstsFeed: '${{ parameters.feedName }}'
#      vstsFeedPackage: '${{ parameters.packageName }}'
#      vstsPackageVersion: '${{ parameters.companyPortalVersion }}'
  - publish: $(Build.ArtifactStagingDirectory)/brokers
    enabled: ${{ parameters.shouldPublishArtifact }}
    displayName: 'Publish as Artifact'
    artifact: ${{ parameters.artifactName }}
  - task: PowerShell@2
    displayName: Add CompanyPortal Version Tag
    inputs:
      targetType: inline
      script: |
        Write-Host "##vso[build.addbuildtag]CompanyPortal-APK-Version=${{ parameters.companyPortalVersion }}"
