parameters:
  - name: msazureServiceConnection
    type: string
    default: 'AndroidBroker-CI'
  - name: msazureFeedName
    type: string
    default: 'Android-Broker'
  - name: artifactPath
    type: string
    default: 'brokers/oldAPKs'
  - name: brokerHostVersion
    type: string
    default: '*'
  - name: packageName
    type: string
    default: 'broker-host'
  - name: artifactName
    type: string
    default: "BrokerHost"
  - name: shouldPublishArtifact
    type: boolean
    default: true

steps:
  - script: mkdir -p brokers
    displayName: 'make brokers dir'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
  - task: UniversalPackages@0
    displayName: 'Download BrokerHost (${{ parameters.brokerHostVersion }})'
    inputs:
      command: 'download'
      downloadDirectory: '$(Build.ArtifactStagingDirectory)/${{ parameters.artifactPath }}'
      feedsToUse: 'external'
      externalFeedCredentials: '${{ parameters.msazureServiceConnection }}'
      feedDownloadExternal: '${{ parameters.msazureFeedName }}'
      packageDownloadExternal: '${{ parameters.packageName }}'
      versionDownloadExternal: '${{ parameters.brokerHostVersion }}'
  - publish: $(Build.ArtifactStagingDirectory)/brokers
    enabled: ${{ parameters.shouldPublishArtifact }}
    displayName: 'Publish as Artifact'
    artifact: ${{ parameters.artifactName }}
