parameters:
  - name: msazureServiceConnection
    type: string
    default: 'AndroidBroker-CI'
  - name: msazureFeedName
    type: string
    default: 'Android-Broker'
  - name: artifactPath
    type: string
    default: 'brokers'
  - name: authenticatorVersion
    type: string
    default: '*'
  - name: packageName
    type: string
    default: 'com.azure.authenticator'
  - name: artifactName
    type: string
    default: "Authenticator"
  - name: shouldPublishArtifact
    type: boolean
    default: true

steps:
  - script: mkdir -p brokers
    displayName: 'make brokers dir'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
  - task: UniversalPackages@0
    displayName: 'Download Authenticator from Feed'
    inputs:
      command: 'download'
      downloadDirectory: '$(Build.ArtifactStagingDirectory)/${{ parameters.artifactPath }}'
      feedsToUse: 'external'
      externalFeedCredentials: '${{ parameters.msazureServiceConnection }}'
      feedDownloadExternal: '${{ parameters.msazureFeedName }}'
      packageDownloadExternal: '${{ parameters.packageName }}'
      versionDownloadExternal: '${{ parameters.authenticatorVersion }}'
  - publish: $(Build.ArtifactStagingDirectory)/brokers
    enabled: ${{ parameters.shouldPublishArtifact }}
    displayName: 'Publish as Artifact'
    artifact: ${{ parameters.artifactName }}
  - task: PowerShell@2
    displayName: Add Authenticator Version Tag
    inputs:
      targetType: inline
      script: |
        Write-Host "##vso[build.addbuildtag]Authenticator-APK-Version=${{ parameters.authenticatorVersion }}"
