parameters:
  - name: artifactPath
    type: string
    default: 'brokers'
  - name: authenticatorVersion
    type: string
    default: '*'
  - name: packageName
    type: string
    default: 'com.azure.authenticator'
  - name: serviceConnection
    type: string
    default: 'AuthClientAndroid-Managed-Identity-WIF-Connection'
  - name: artifactName
    type: string
    default: "Authenticator"
  - name: shouldPublishArtifact
    type: boolean
    default: true

steps:
  - script: mkdir -p brokers
    displayName: 'make brokers dir'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
  - task: AzureCLI@2
    displayName: Download Authenticator from External feed with Service Connection
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az artifacts universal download --organization https://msazure.visualstudio.com/ --feed Android-Broker --name ${{ parameters.packageName }} --version ${{ parameters.authenticatorVersion }} --path $(Build.ArtifactStagingDirectory)/${{ parameters.artifactPath }}
  - publish: $(Build.ArtifactStagingDirectory)/brokers
    enabled: ${{ parameters.shouldPublishArtifact }}
    displayName: 'Publish as Artifact'
    artifact: ${{ parameters.artifactName }}
  - task: PowerShell@2
    displayName: Add Authenticator Version Tag
    inputs:
      targetType: inline
      script: |
        Write-Host "##vso[build.addbuildtag]Authenticator-APK-Version=${{ parameters.authenticatorVersion }}"
