parameters:
  - name: feedName
    type: string
    default: 'AndroidADAL'
  - name: artifactPath
    type: string
    default: 'brokers'
  - name: brokerHostVersion
    type: string
    default: '*'
  - name: packageName
    type: string
    default: 'com.microsoft.identity.testuserapp'
  - name: artifactName
    type: string
    default: "BrokerHost"
  - name: shouldPublishArtifact
    type: boolean
    default: true

steps:
  - script: mkdir -p brokers
    displayName: 'make brokers dir'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
  - task: UniversalPackages@0
    displayName: 'Download BrokerHost (${{ parameters.brokerHostVersion }})'
    inputs:
      command: 'download'
      downloadDirectory: '$(Build.ArtifactStagingDirectory)/${{ parameters.artifactPath }}'
      feedsToUse: 'internal'
      vstsFeed: '${{ parameters.feedName }}'
      vstsFeedPackage: '${{ parameters.packageName }}'
      vstsPackageVersion: '${{ parameters.brokerHostVersion }}'
  - publish: $(Build.ArtifactStagingDirectory)/brokers
    enabled: ${{ parameters.shouldPublishArtifact }}
    displayName: 'Publish as Artifact'
    artifact: ${{ parameters.artifactName }}
