parameters:
  - name: LTWVersion
    type: string
    default: '*'
  - name: artifactPath
    type: string
    default: 'brokers'
  - name: packageName
    type: string
    default: 'com.microsoft.appmanager'
  - name: serviceConnection
    type: string
    default: 'AuthClientAndroid-Managed-Identity-WIF-Connection'
  - name: apkName
    type: string
    default: 'LTW-signed.apk'
  - name: artifactName
    type: string
    default: "LTW"
  - name: shouldPublishArtifact
    type: boolean
    default: true

steps:
  - script: mkdir -p brokers
    displayName: 'make brokers dir'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
  - task: AzureCLI@2
    displayName: Download LTW from External feed with Service Connection
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az artifacts universal download --organization https://microsoft.visualstudio.com/ --feed Auth-Broker-Integrated-LTW-Build --name ${{ parameters.packageName }} --version ${{ parameters.LTWVersion }} --path $(Build.ArtifactStagingDirectory)/${{ parameters.artifactPath }}
  - script: mv ./YPC-*.apk ./${{ parameters.apkName }}
    displayName: 'Rename LTW apk (${{parameters.apkName}})'
    workingDirectory: '$(Build.ArtifactStagingDirectory)/${{ parameters.artifactPath }}'
  - publish: $(Build.ArtifactStagingDirectory)/brokers
    enabled: ${{ parameters.shouldPublishArtifact }}
    displayName: 'Publish as Artifact'
    artifact: ${{ parameters.artifactName }}
  - task: PowerShell@2
    displayName: Add LTW Version Tag
    inputs:
      targetType: inline
      script: |
        Write-Host "##vso[build.addbuildtag]LTW-APK-Version=${{ parameters.LTWVersion }}"
