# File: automation-cert.yml

steps:
  - task: AzureKeyVault@2
    displayName: 'Azure Key Vault: Download Cert for Automation'
    inputs:
      azureSubscription: 'AuthSdkResourceManager'
      KeyVaultName: 'msidlabs'
      SecretsFilter: 'LabVaultAccessCert'

  - task: Bash@3
    displayName: Install Automation Cert
    inputs:
      targetType: inline
      script: |
        echo "Decoding and exporting certificate"
        
        # Decode base64 encoded certificate
        echo "$LabVaultAccessCert" | base64 -d > $(Build.SourcesDirectory)/LabVaultAccessCert.pfx
        
        # Verify the certificate file creation
        if [ -f "$(Build.SourcesDirectory)/LabVaultAccessCert.pfx" ]; then
          echo "The needed PFX file created successfully at $(Build.SourcesDirectory)/LabVaultAccessCert.pfx"
        else
          echo "Failed to create the needed PFX file at $(Build.SourcesDirectory)/LabVaultAccessCert.pfx"
          exit 1
        fi
  
        # Set the certificate path as an environment variable for later steps
        certPathVar=$(Build.SourcesDirectory)/LabVaultAccessCert.pfx
        echo "##vso[task.setvariable variable=LabVaultAppCert]$certPathVar"
        echo "##vso[task.setvariable variable=LabVaultAppCert;isOutput=true]$certPathVar"
