# File: automation-cert.yml

steps:
  - task: AzureKeyVault@2
    displayName: 'Azure Key Vault: Download Cert for Automation'
    inputs:
      azureSubscription: 'AuthSdkResourceManager'
      KeyVaultName: 'msidlabs'
      SecretsFilter: 'LabVaultAccessCert'

  - task: Bash@3
    displayName: Install Automation Cert
    inputs:
      targetType: inline
      script: |
        echo "Decoding and exporting certificate"
        
        # Decode base64 encoded certificate
        echo "$LabVaultAccessCert" | base64 -d > $(Build.SourcesDirectory)/LabVaultAccessCert.pfx
        
        cert_path=$(Build.SourcesDirectory)/LabVaultAccessCert.pfx
        
        if [ -f "$cert_path" ]; then
          echo "PFX file created successfully at certpath : $cert_path"
          echo "##vso[task.setvariable variable=LabVaultAppCert;isOutput=true]$cert_path"
        else
          echo "Failed to create PFX file at $cert_path"
          exit 1
        fi
