# File: azure-pipelines\templates\docker-instrumented-test.yml
# Description: Template to run Instrumented test for Supported API levels

parameters:
- name: acrImage
  default: authclient.azurecr.io/samples/dbi-instrumented-api30
- name: androidProject
  default: self
- name: EnvVstsMvnAccount
  default: ''

steps:
- task: PostBuildCleanup@3
  condition: always()
  displayName: 'Post build clean up'
- checkout: ${{ parameters.androidProject }}
  clean: true
  submodules: recursive
- script: touch env.list
  displayName: 'Create Enviroment file'
- script: echo "${{ parameters.EnvVstsMvnAccount }}=$(mvnAccessToken)" >> env.list
  condition: ne('${{ parameters.EnvVstsMvnAccount }}', '')
  displayName: set mvnAccessToken
- script: |
    if docker image inspect $DOCKERIMAGE; then
      echo "Image is already installed"
    else
      echo "Image is not installed... Pulling $DOCKERIMAGE"
      docker pull $DOCKERIMAGE
    fi
  env:
    DOCKERIMAGE: ${{ parameters.acrImage }}
  displayName: Pulling Image from ACR
- script: |
    docker --version
    echo =============================================
    echo Kill all running containers if existing
    echo =============================================
    docker container kill $(docker ps -q)
    echo =============================================
    echo Run unit and instrumented inside docker container
    echo =============================================
    docker run --privileged --env-file env.list --cpus="3" --memory="12g" -v "$PWD":/home/gradle/ -w /home/gradle/ $DOCKERIMAGE sh scripts/run-instrumented-tests.sh
  env:
    DOCKERIMAGE: ${{ parameters.acrImage }}
  displayName: 'Build and test inside docker container'
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    displayName: 'Publish Test Results'
    mergeTestResults: false
    testRunTitle: '${{ parameters.androidProject }} ${{ parameters.acrImage }}'
- script: |
    echo =============================================
    echo Kill all running containers if existing
    echo =============================================
    docker container kill $(docker ps -q)
    echo =============================================
    echo Cleaning up build output that is owned by docker user rather than agent user
    echo =============================================
    docker run --privileged --env-file env.list --cpus="3" --memory="12g" -v "$PWD":/home/gradle/ -w /home/gradle/ $DOCKERIMAGE gradle --stop
    docker run --privileged --env-file env.list --cpus="3" --memory="12g" -v "$PWD":/home/gradle/ -w /home/gradle/ $DOCKERIMAGE gradle clean
    echo =============================================
    echo prune containers to avoid running out of disk space - shutdown containers still exist on disk
    echo =============================================
    docker system prune --volumes -f
    echo =============================================
    echo Dump environment variables for build agent
    echo =============================================
    env
    echo =============================================
    echo Docker status
    echo =============================================
    docker system df
  env:
    DOCKERIMAGE: ${{ parameters.acrImage }}
  condition: always()
  displayName: 'Cleanup'
