# A template used to generate an access token corresponding to a given service connection

parameters:
  - name: serviceConnection
    type: string
    default: Managed-Identity-WIF-Connection
  - name: tokenVariableName
    type: string

steps:
  - task: AzureCLI@2
    displayName: Set up Access Token From Service Connection
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # if this fails, check out this bash script that includes diagnostics:
        # https://gist.github.com/johnterickson/19f80a3e969e39f1000d118739176e62

        # Note that the resource is specified to limit the token to Azure DevOps
        $accessToken = az account get-access-token --query accessToken --resource 499b84ac-1321-427f-aa17-267ca6975798 -o tsv

        # Set the access token as a secret, so it doesn't get leaked in the logs
        Write-Host "##vso[task.setsecret]$accessToken"
        Write-Host "##vso[task.setvariable variable=${{ parameters.tokenVariableName }}]$accessToken"
