
name: 1.0.$(Date:yyyyMMdd)-test$(Rev:.r) # $(Build.BuildNumber) = name

pr: none
trigger: none

resources:
  repositories:
    - repository: common
      type: github
      name: AzureAD/microsoft-authentication-library-common-for-android
      ref: dev
      endpoint: ANDROID_GITHUB
    - repository: broker
      type: github
      name: AzureAD/ad-accounts-for-android
      ref: dev
      endpoint: ANDROID_GITHUB
    - repository: msal
      type: github
      name: AzureAD/microsoft-authentication-library-for-android
      ref: dev
      endpoint: ANDROID_GITHUB
    - repository: adal
      type: github
      name: AzureAD/azure-activedirectory-library-for-android
      ref: dev
      endpoint: ANDROID_GITHUB
    - repository: azuresample
      type: github
      name: Azure-Samples/ms-identity-android-java
      ref: master
      endpoint: ANDROID_GITHUB

parameters:
  - name: customVersionNumber
    displayName: Version Number
    type: string
    default: Default
  - name: flightingSelection
    displayName: Broker Flight Provider (ECS is used in PROD)
    type: string
    default: "Local"
    values:
      - Local
      - ECS
  - name: flightingValueParameter
    displayName: Broker Local Flight Json-String (not active with ECS flighting)
    type: string
    default: '{EnablePrtV3:true,EnableBrokerPowerLiftLogging:true}'
  - name: flagsValue
    displayName: Flags to Pass (passed to all libraries)
    type: string
    default: ' '
  - name: shouldRunUiValidation
    displayName: Run E2E UI Validation?
    type: boolean
    default: False
  - name: shouldRunUnitAndInstrumentedTests
    displayName: Run Unit and Instrumented Tests?
    type: boolean
    default: True
  - name: shouldEnableBrokerSelectionAndDiscoveryFlag
    displayName: Should enable broker selection & discovery?
    type: boolean
    default: False
  - name: shouldTrustDebugBroker
    displayName: (FOR DEBUGGING) Always trust debug broker apps. (Required for working with DEBUG CP/LTW/AuthApp)
    type: boolean
    default: false
  - name: treatTestAppAsPartOfTSL
    displayName: (FOR DEBUGGING) Force Broker to treat OneAuthTestApp/MSALTestApp as first party app. (Required for testing with 1st party app registration)
    type: boolean
    default: False
  - name: publishLibraryArtifacts
    displayName: Should publish library artifacts? (lockfiles and release artifacts)
    type: boolean
    default: false
  - name: msalTestTarget
    displayName: Test Targets for MSAL
    type: string
    default: package com.microsoft.identity.client.msal.automationapp.testpass.broker, package com.microsoft.identity.client.msal.automationapp.testpass.msalonly, notAnnotation org.junit.Ignore, notAnnotation com.microsoft.identity.client.ui.automation.annotations.FailsWithDailyVersions, notAnnotation com.microsoft.identity.client.ui.automation.annotations.DoNotRunOnPipeline
  - name: brokerTestTarget
    displayName: Test Targets for Broker
    type: string
    default: package com.microsoft.identity.client.broker.automationapp.testpass, notAnnotation org.junit.Ignore, notAnnotation com.microsoft.identity.client.ui.automation.annotations.FailsWithDailyVersions, notAnnotation com.microsoft.identity.client.ui.automation.annotations.DoNotRunOnPipeline

variables:
  ${{ if eq(parameters.customVersionNumber, 'Default') }}:
    versionNumber: $[variables['build.buildnumber']]
    brokerVersionNumber: $[replace(variables['build.buildnumber'], '1.0.', '8.1.')]
  ${{ else }}:
    versionNumber:  ${{ parameters.customVersionNumber }}
    brokerVersionNumber: $[replace('${{ parameters.customVersionNumber }}', '1.0.', '8.1.')]
  projVersionParam: -PprojVersion=$(versionNumber)
  common4jVersionParam: -PdistCommon4jVersion=$(versionNumber)
  broker4jVersionParam: -PdistBroker4jVersion=$(versionNumber)
  commonVersionParam: -PdistCommonVersion=$(versionNumber)
  linuxBrokerVersion: -PlinuxBrokerVersion=$(versionNumber)
  androidProjectDependencyParam: --configuration=distReleaseRuntimeClasspath --write-locks
  javaProjectDependencyParam: --configuration=runtimeClasspath --write-locks
  authenticatorPipelineId: 237369
  companyPortalPipelineId: 237827
  ltwPipelineId: 44201
  brokerAutomationPipelineId: 1490
  # We add these flags during scheduled runs, they will be dropped depending on the day of the week
  ${{ if or(parameters.shouldEnableBrokerSelectionAndDiscoveryFlag, eq( variables['Build.Reason'], 'Schedule')) }}:
    enableBrokerSelectionParam: -PbrokerSelectionEnabledFlag
    enableBrokerDiscoveryParam: -PnewBrokerDiscoveryEnabledFlag
  ${{ else }}:
    enableBrokerSelectionParam: ''
    enableBrokerDiscoveryParam: ''
  ${{ if or(parameters.shouldTrustDebugBroker, eq( variables['Build.Reason'], 'Schedule')) }}:
    trustDebugBrokerParam: -PtrustDebugBrokerFlag
  ${{ else }}:
    trustDebugBrokerParam: ''
  ${{ if or(parameters.treatTestAppAsPartOfTSL, eq( variables['Build.Reason'], 'Schedule')) }}:
    bypassRedirectUriCheckParam: -PbypassRedirectUriCheck
    treatTestAppAsPartOfTSLParam: -PtreatTestAppAsPartOfTSL
  ${{ else }}:
    bypassRedirectUriCheckParam: ''
    treatTestAppAsPartOfTSLParam: ''
  brokerHostPackageVersionCounter: $[counter(1, 10000)]
  nameSuffix: "test"

stages:
- stage: 'setupStage'
  displayName: Setup Stage
  dependsOn: []
  condition: always() # Stage will always run
  jobs:
    - template: ./templates/tagBuild/tag-daily-build.yml
      parameters:
        flightingValueParameter: ${{ parameters.flightingValueParameter }}
        flightingSelection: ${{ parameters.flightingSelection }}
        flagsValue: ${{ parameters.flagsValue }}
        versionNumber: $(versionNumber)
        brokerVersionNumber: $(brokerVersionNumber)
        buildingOnSchedule: $[eq( variables['Build.Reason'], 'Schedule')]
        DayOfWeek: $(DayOfWeek)
        enableBrokerSelectionParam: $(enableBrokerSelectionParam)
        enableBrokerDiscoveryParam: $(enableBrokerDiscoveryParam)
        trustDebugBrokerParam: $(trustDebugBrokerParam)
        bypassRedirectUriCheckParam: $(bypassRedirectUriCheckParam)
        treatTestAppAsPartOfTSLParam: $(treatTestAppAsPartOfTSLParam)

# Build and publish libraries
- template: ./templates/buildProduct/build-and-publish-auth-android-libs.yml
  parameters:
    versionNumber: $(versionNumber)
    brokerVersionNumber: $(brokerVersionNumber)
    buildFlags: $[ stageDependencies.setupStage.alternateSchedule.outputs['finalSetupScript.finalFlag'] ]
    flightFlags: $[ stageDependencies.setupStage.alternateSchedule.outputs['finalSetupScript.finalFlight'] ]
    powerliftApiKey: $(powerliftApiKey)
    shouldRunUnitAndInstrumentedTests: ${{ parameters.shouldRunUnitAndInstrumentedTests }}

# Build and publish broker apps
- template: ./templates/buildBrokerApps/build-broker-apps.yml
  parameters:
    versionNumber: $(versionNumber)
    brokerVersionNumber: $(brokerVersionNumber)
    authenticatorBranch: "somalaya/fixLoggerIssue"

# Build and publish test apps
- stage: 'testappgeneration'
  dependsOn:
    - publishAdal
    - publishCommonLibraries
    - publishMsal
    - publishBrokerLibraries
    - promotePackages
    - setupStage
  displayName: Generate Test Apps
  condition:
    and
    (
    not(failed()),
    not(canceled())
    )
  jobs:
    - template: ./templates/buildTestApps/build-test-apps.yml
      parameters:
        versionNumber: $(versionNumber)
        brokerVersionNumber: $(brokerVersionNumber)
        brokerHostPackageCounter: $(brokerHostPackageVersionCounter)
        buildFlags: $[ stageDependencies.setupStage.alternateSchedule.outputs['finalSetupScript.finalFlag'] ]
        flightFlags: $[ stageDependencies.setupStage.alternateSchedule.outputs['finalSetupScript.finalFlight'] ]

# Run Daily Automation Tests
- template : ./templates/runTests/run-daily-automation.yml
  parameters:
    msalTestTarget: ${{ parameters.msalTestTarget }}
    brokerTestTarget: ${{ parameters.brokerTestTarget }}
    testRunPrefix: ""
...
