
name: $(date:yyyyMMdd)$(rev:.r)

trigger: none
pr: none

resources:
  containers:
  - container: mycontainer  # identifier (A-Z, a-z, 0-9, and underscore)
    type: ACR # type of the registry like ACR, GCR etc. 
    azureSubscription: AuthClient # Azure subscription (ARM service connection) for container registry;
    resourceGroup: AuthClientAzureContainers # resource group for your ACR
    registry: authclient.azurecr.io # registry for container images
    repository: samples/dbi-instrumented-api30 # name of the container image repository in ACR

    #image: string  # container image name
    #options: string  # arguments to pass to container at startup
    #endpoint: string  # reference to a service connection for the private registry
    #env: { string: string }  # list of environment variables to add
    #ports: [ string ] # ports to expose on the container
    #volumes: [ string ] # volumes to mount on the container
    #mapDockerSocket: bool # whether to map in the Docker daemon socket; defaults to true
    #mountReadOnly:  # volumes to mount read-only - all default to false
    #  externals: boolean  # components required to talk to the agent
    #  tasks: boolean  # tasks required by the job
    #  tools: boolean  # installable tools like Python and Ruby
    #  work: boolean # the work directory


jobs:
- job: test
  displayName: test
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - checkout: none
  - script: printenv