
name: $(date:yyyyMMdd)$(rev:.r)

trigger: none
pr: none

resources:
  containers:
  - container: mycontainer
    image: authclient.azurecr.io/samples/dbi-instrumented-api30:latest
    endpoint: AuthClient


    #options: string  # arguments to pass to container at startup
    #env: { string: string }  # list of environment variables to add
    #ports: [ string ] # ports to expose on the container
    #volumes: [ string ] # volumes to mount on the container
    #mapDockerSocket: bool # whether to map in the Docker daemon socket; defaults to true
    #mountReadOnly:  # volumes to mount read-only - all default to false
    #  externals: boolean  # components required to talk to the agent
    #  tasks: boolean  # tasks required by the job
    #  tools: boolean  # installable tools like Python and Ruby
    #  work: boolean # the work directory


jobs:
- job: test
  displayName: test
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - checkout: none
  - script: printenv
  - script: echo |
      echo $(resources.container.mycontainer.type)
      echo $(resources.container.mycontainer.registry)
      echo $(resources.container.mycontainer.repository)
      echo $(resources.container.mycontainer.tag)
      echo $(resources.container.mycontainer.digest)
      echo $(resources.container.mycontainer.URI)
      echo $(resources.container.mycontainer.location)
    target:
      container: mycontainer
  - script: echo "I can run inside the container (it starts by default)"
  - task: Docker@2
    inputs:
      command: stop
      container: mycontainer