# File: azure-pipelines\build-android-complete.yml
# Description: TODO
name: $(date:yyyyMMdd)$(rev:.r)

trigger: none
pr: none

pool:
  name: Hosted Windows 2019 with VS2019

jobs:
  - job: droidSetup
    displayName: Perform droidSetup
    steps:
      - checkout: self
        clean: true
        persistCredentials: True
      - powershell: |
          # Include the .gitconfig file included with project to your local gitconfig
          git config --local include.path ../.gitconfig
          # Run this newly minted command to clone each repo as a subfolder
          git droidSetup
        #errorActionPreference: continue
        displayName: 'Setup Android Complete'
...
